### PR TITLE
privData needs to padded with bytes not str

### PR DESCRIPTION
**Pull request by benkiel**
One letter, but an important one.

### CODE REVIEW

**Comment by behdad** [comment]
How did this ever work?!

**Comment by anthrotype** [comment]
ouch. thanks

looks like this wasn't covered by tests. Mind adding a simple one somewhere?

**Comment by anthrotype** [comment]
> How did this ever work?!

it didn't 😅

**Comment by benkiel** [comment]
@anthrotype in the middle of trying to get out a font release, tbh. Will try to come back and make a test later this week

**Comment by benkiel** [comment]
@anthrotype where would be best to put a test? 

I can see either putting it in `main_test.py` for `ttLib` or in `sfnt_test.py` — the first is easier as it already has methods for getting a font object to use, and it tests WOFF a bit already, but the direct place is `sfnt_test.py`. (yes, there could also be `woff_test.py` but that's the most work.

**Comment by anthrotype** [comment]
Where it's more convenient to you, any test is better than nothing thanks

**Comment by benkiel** [comment]
@anthrotype ok, test added

**Comment by benkiel** [comment]
Ok to merge?

**Review by anthrotype — APPROVED** [review]
LGTM thanks!

**Pull request merged**
