### PR TITLE
[glyf] Add optimizeSize option

### PR DESCRIPTION
**Pull request by behdad**
Set to True by default. Can be turned to False on the table.

### CODE REVIEW

**Review by khaledhosny — APPROVED** [review]
LGTM, but probably needs some tests.

**Comment by Lorp** [comment]
To confirm, this allows the glyph to be written as a u8[numPoints] flags, i16[numPoints] xCoords, i16[numPoints] yCoords?

**Comment by behdad** [comment]
> To confirm, this allows the glyph to be written as a u8[numPoints] flags, i16[numPoints] xCoords, i16[numPoints] yCoords?

Something like that. Might be i8 for xCoords / yCoords permitting... And of course runs are limited to 256 entries at a time.

**Comment by Lorp** [comment]
What runs in glyf? Ah, this is the gvar deltas thing? I assumed you were talking glyf because of "[glyf]" in the subject :) Writing uncompressed glyf is quicker, and 100% beneficial if immediately converting to WOFF2.

**Comment by behdad** [comment]
> What runs in glyf? Ah, this is the gvar deltas thing? I assumed you were talking glyf because of "[glyf]" in the subject :) Writing uncompressed glyf is quicker, and 100% beneficial if immediately converting to WOFF2.

It *is* glyf. The flags repeat goes up to 255 only, so every 256 items need a new flag...

**Comment by Lorp** [comment]
If writing uncompressed, why set the repeat bit at all?

**Comment by behdad** [comment]
> If writing uncompressed, why set the repeat bit at all?

Oh compressing the repeat is faster I think to process, since you can have one loop per repeat, instead of loop iterations on each coordinate.

**Comment by Lorp** [comment]
In Samsa I found quite significant speedups in writing glyf entirely uncompressed, since I know in advance where to write xCoords and yCoords.

**Comment by behdad** [comment]
> In Samsa I found quite significant speedups in writing glyf entirely uncompressed, since I know in advance where to write xCoords and yCoords, and can do so in a single loop.

I saw about 5% speedup decoding the results of this PR. That's without any special coding...

**Comment by Lorp** [comment]
Ah ok, I was concerned with improving encoding speed.

**Pull request merged**
