### PR TITLE
[interpolatablePlot] Draw summary / index / table of contents

### PR DESCRIPTION
**Pull request by behdad**

### CODE REVIEW

**Comment by behdad** [comment]
Sample output:
[out.pdf](https://github.com/fonttools/fonttools/files/13668020/out.pdf)

**Comment by MariannaPaszkowska** [comment]
HI Behdad, when I try to select/copy/paste text from the PDF (legend or anywhere else) I'm getting mirrored output: "ruotnoc eht ni knik gnisuac tnioP", ":dnegeL"

**Comment by MariannaPaszkowska** [comment]
I think that a list of all glyphs with issues would be helpful to print out. Then, it will be easy to copy those and put them in a text editor to test them all together). I suggest this format: "asterisk 002A *".

**Comment by MariannaPaszkowska** [comment]
Also, the legend is very helpful, but it would be even better to print in each issue, somewhere next to the "midway interpolation", the list of all issues in this glyph. Example: "midway interpolation", then "Kink, Contur start point issue, Wrong contour order", etc.

**Comment by behdad** [comment]
> I think that a list of all glyphs with issues would be helpful to print out. Then, it will be easy to copy those and put them in a text editor to test them all together). I suggest this format: "asterisk 002A *".

That's what I put in the Summary page. Or do you mean print out to the terminal?

**Comment by behdad** [comment]
> Also, the legend is very helpful, but it would be even better to print in each issue, somewhere next to the "midway interpolation", the list of all issues in this glyph. Example: "midway interpolation", then "Kink, Contur start point issue, Wrong contour order", etc.

But that's written on top of each page.

**Comment by behdad** [comment]
> HI Behdad, when I try to select/copy/paste text from the PDF (legend or anywhere else) I'm getting mirrored output: "ruotnoc eht ni knik gnisuac tnioP", ":dnegeL"

Yeah this seems to be an issue with the Apple PDF Preview app. Try opening the PDF in Chrome for example and observe that it copies correctly. You can also `brew install evince` and use `evince out.pdf`.

**Pull request merged**
