### PR TITLE
Handle implicit CFF2 closepath within T2OutlineExtractor

### PR DESCRIPTION
**Pull request by skef**
The very recently merged PR #2577 fixes the direct issue of #2455 and the surface issue in close-to-duplicate #1899 but the problem remains for any code inheriting from or using `T2OutlineExtractor` outside of the `T2CharString` context. The way things are left anyone making other use of `T2OutlineExtractor` also needs to add an `endPath()` call after calling `execute()` -- an undocumented and unusual requirement -- to work correctly with CFF2.

Other questions aside, from a basic object encapsulation standpoint it seems better to handle the issue from within T2OutlineExtractor (which is the level at which `closePath()` starts to be supported) rather than outside of it. 

This PR represents one approach, already discussed a bit in #1899 . I won't pretend this fills me with engineering joy -- it feels kind of grubby. But it works, both in terms of the test suite and my relevant code.

About that test suite -- it also passes without the `isSubr` addition, implying that there are no current tests catching spurious `closePath()`s. I'm willing to try to construct such a test as part of this PR assuming a bit of guidance.

### CODE REVIEW

**Comment by skef** [comment]
This approach works as well. Would it make anyone happier?

```
diff --git a/Lib/fontTools/misc/psCharStrings.py b/Lib/fontTools/misc/psCharStrings.py
index 6014abc2..4e89b690 100644
--- a/Lib/fontTools/misc/psCharStrings.py
+++ b/Lib/fontTools/misc/psCharStrings.py
@@ -502,11 +502,20 @@ class T2OutlineExtractor(T2WidthExtractor):
                T2WidthExtractor.__init__(
                        self, localSubrs, globalSubrs, nominalWidthX, defaultWidthX, private)
                self.pen = pen
+               self.subrLevel = 0
 
        def reset(self):
                T2WidthExtractor.reset(self)
                self.currentPoint = (0, 0)
                self.sawMoveTo = 0
+               self.subrLevel = 0
+
+       def execute(self, charString):
+               self.subrLevel += 1
+               super().execute(charString)
+               self.subrLevel -= 1
+               if self.subrLevel == 0:
+                       self.endPath()
 
        def _nextPoint(self, point):
                x, y = self.currentPoint
```

**Comment by justvanrossum** [comment]
Yeah, that feels a bit cleaner indeed.

A concern I had earlier while discussing #2455 that still stands: I wonder if we can avoid calling closePath twice for CFF by changing this:

https://github.com/fonttools/fonttools/blob/169731c7f5d96e96d531d35db477af5e727fe945/Lib/fontTools/misc/psCharStrings.py#L537-L540

into this:

```python
	def endPath(self):
		# In T2 there are no open paths, so always do a closePath when
		# finishing a sub path.
		if self.sawMoveTo:
			self.closePath()
```

**Comment by justvanrossum** [comment]
(My last suggestion may be better in a new PR, as it's more of a followup to #2577 really, so feel free to ignore.)

**Comment by skef** [comment]
@justvanrossum I'll redo this PR and take a look at that `closePath()` question as part of it.

**Comment by skef** [comment]
OK, the PR is updated

**Review by justvanrossum — APPROVED** [review]
LGTM

**Pull request merged**
