### PR TITLE
[pointPens] Add {Filter,Recording,Transform,Rounding}PointPen

### PR DESCRIPTION
**Pull request by anthrotype**
This PR adds a few point pens that are equivalent to the corresponding (segment) pens:

- FilterPointPen: passes through points/components unchanged to another 'slave' pen; mostly used as base class for more interesting filter pens, such as..
- TransformPointPen: a filter point pen that takes an Affine transforms and another point pen;
- RoundingPointPen: filter point pen that rounds point coordinates and components' offsets to integer;
- RecordingPointPen: records and replays point-pen commands (beginPath, addPoint, endPath)

### CODE REVIEW

**Comment by justvanrossum** [comment]
Have you looked at the RecordingPointPen and TransformPointPen implementations from https://github.com/robotools/fontPens/tree/master/Lib/fontPens?

**Comment by anthrotype** [comment]
oops.. I didn't 😅 
lemme have a look and see if I can merge them with mine

**Comment by anthrotype** [comment]
Ok, the TransformPointPen and RecordingPointPen now work the same as the ones from fontPens package. The only difference with my original implementation was that I included `identifier` in the positional argument and didn't have a slot for the extra `kwargs`. But I agree it's safer not to assume identifier is a positional arg (as it was introduced later), and it's good to keep the kwargs.

I haven't added the `replayRecording` method. Do we need one? Probably not.

**Comment by justvanrossum** [comment]
> I haven't added the replayRecording method. Do we need one? Probably not.

I added that for symmetry with recordingPen.py, but I don't think I've ever used it.

What would be a great is a PR for fontPens that imports the ones from fonttools, and issues a deprecation warning upon import. It's a bit silly to keep both.

**Comment by anthrotype** [comment]
> What would be a great is a PR for fontPens that imports the ones from fonttools, and issues a deprecation warning upon import. It's a bit silly to keep both.

Sure, that can be done once these are merged.
Let me know if you have other comments, or I'll go on with the merge.

**Pull request merged**
