### PR TITLE
Fix CursivePos subtable overflows

### PR DESCRIPTION
**Pull request by dscorbett**

### CODE REVIEW

**Comment by behdad** [comment]
Did you got this error, or just implemented it?

This doesn't work. At least not with HarfBuzz. Two neighboring glyphs with their EntryExit records in different subtables will NOT attach.

**Comment by dscorbett** [comment]
I got this error. I guess I’ll have to think of a different solution.

**Comment by behdad** [comment]
Interesting.  For one script?

**Comment by dscorbett** [comment]
Yes, for Duployan. It has a lot of contextual variants.

**Comment by dscorbett** [comment]
When a shaper is checking coverage to choose a subtable in a CursivePos lookup, does it consider both the exit and entry glyphs, just the exit glyph, or just the entry glyph?

**Comment by behdad** [comment]
> When a shaper is checking coverage to choose a subtable in a CursivePos lookup, does it consider both the exit and entry glyphs, just the exit glyph, or just the entry glyph?

Just one.  It used to be checking the entry.  But @mhosken reported that Windows seem to be doing it the other way, so we changed it.  It checks the exit glyph and looks backward now.

**Comment by dscorbett** [comment]
Right: by “table” I meant “lookup”.

**Comment by behdad** [comment]
I'll close this then, until a better solution comes up.

**Pull request closed without merging**
