### PR TITLE
Hatch: How does it work???

### PR DESCRIPTION
**Pull request by madig**
Test driving hatch.

### CODE REVIEW

**Comment by anthrotype** [comment]
I don't know this hatch tool, and am not convinced we need to ditch setuptools or tox 🤔

**Comment by madig** [comment]
Aaargh. I clicked the wrong button, this was supposed to stay in the dama fork because I'm just playing around. Sorry for the noise.

**Comment by behdad** [comment]
What does it do though? :)

**Comment by madig** [comment]
It's an exciting new tool that combines aspects of Peotry and Tox and a couple other things to make Python project management easier and it's already adopted by the PyPA. It fixes a couple things that annoy me about Poetry so I'm keen to try it out :)

**Pull request closed without merging**
