### PR TITLE
[varStore] Improve optimize algorithm

### PR DESCRIPTION
**Pull request by behdad**
This was always supposed to be how it works, but was missed in the initial implementation apparently.

I should probably add extensive tests for the optimization algorithm...

### CODE REVIEW

**Comment by behdad** [comment]
Saves 408 bytes building NotoSansArabic.

**Comment by anthrotype** [comment]
hm in the absence of a test that touches those lines, it's a bit too hard for me to reivew so I'll pass. feel free to merge, this is your code

**Comment by behdad** [comment]
Adding Jany and Nikolaus in case one of them wants to read and understand the algorithm.  I'm willing to add more comments. And yes I'll think about adding tests.

**Comment by rsheeter** [comment]
The doc comment is most appreciated. +1 to tests.

> Saves 408 bytes building NotoSansArabic.

Are there cases where it saves more?

**Comment by behdad** [comment]
> The doc comment is most appreciated. +1 to tests.
> 
> > Saves 408 bytes building NotoSansArabic.
> 
> Are there cases where it saves more?

In NotoSans it saved 2kb, but that's 0.1%.  For NotoSansArabic it was 0.5%. I don't expect it to be much, but hey, it's free savings.

**Comment by behdad** [comment]
> In NotoSans it saved 2kb

Another bugfix (thanks to new tests), and it saves 4.5kb now.

**Comment by behdad** [comment]
> Saves 408 bytes building NotoSansArabic.

Now at 936 bytes after a few other fixes.

**Pull request merged**
