### PR TITLE
Add TTF2OTF snippet

### PR DESCRIPTION
**Pull request by ftCLI**
This pull request adds a snippet to convert TTF fonts to OTF.

### CODE REVIEW

**Comment by behdad** [comment]
Thanks for this.

My only feedback is that it would be nice to do it without click.

**Comment by behdad** [comment]
Well, and move it to an actual module, instead of Snippets.

**Comment by ftCLI** [comment]
> Well, and move it to an actual module, instead of Snippets.

In which module should I move it? `qu2cu` seems the natural location.

Ok to rewrite the CLI with argparse. Is it ok to keep the `cffsubr` dependency or should it be removed too?

**Comment by behdad** [comment]
> > Well, and move it to an actual module, instead of Snippets.
> 
> In which module should I move it? `qu2cu` seems the natural location.

I think `ttLib` is best.

> Ok to rewrite the CLI with argparse. Is it ok to keep the `cffsubr` dependency or should it be removed too?

`cffsubr` can stay, as an optional dependency.

**Comment by ftCLI** [comment]
Hi,

I've replaced `click` with `argparse`. Regarding moving the snippet to `ttLib`, I'm not sure. It does what the `Snippets/otf2ttf.py` does, but in the opposite direction.

**Comment by behdad** [comment]
Can you please run `black` on it, to fix the lint test? Looks good to me otherwise.

**Pull request merged**
