### PR TITLE
Drop Python3.7, require 3.8+ and run tests on 3.11 too

### LINKED ISSUE #2878: drop support for 3.7?
Python 3.7 is EOL in about 7 months in June 2023 (see https://endoflife.date/python)

Other popular projects like numpy or scipy are already requiring Python 3.8 in their latest versions.

I think we can do the same without waiting for June 2023. Any objections?

### PR DESCRIPTION
**Pull request by anthrotype**
Fixes #2878 and #2163

### CODE REVIEW

**Comment by anthrotype** [comment]
We currently test the minimum and maximum required pythons, previously it was 3.7 (on linux only) and 3.10 (on all of linux, mac and windows).
Initially, in this PR, I tried to bump those to 3.8 (linux) and 3.11 (linux, mac, win), but encountered issues because lxml (again!) doesn't provide wheels for 3.11 for all three. So I reverted to testing 3.10 on linux, mac and windows for the main test suite. 
I still left one CI build that's using Python 3.11, that's the one that tests building the cython modules, and only runs on linux and runs test that don't require lxml so it worked in that case.

So this is ready to be merged, provided everyone is happy about dropping support for Python 3.7.
I will interpret silence as consent if nobody raises concerns within a couple days time.

**Comment by madig** [comment]
I'm wondering if we want to start using pip-tools for requirements management? The text files seem handwritten to me currently, and some deps are pinned in tox instead. We could instead pip-compile several requirements files ready to be used as is in testing? Then there's one way to do dep testing.

**Comment by anthrotype** [comment]
sounds good, wanna send a PR?

**Comment by anthrotype** [comment]
I just reverted this PR with https://github.com/fonttools/fonttools/commit/f21e6768a7e970e3ec0f3c4b818f47f8dfd1c92b. We shall re-revert once a new RoboFont is released, which I hear will use (at least) Python 3.9. I can't speak of Robofont schedule, but I would like to be able to drop Python 3.7 support by the end of this year.

**Pull request merged**
