### PR TITLE
[t2CharStringPen] Add support for more path operators

### PR DESCRIPTION
**Pull request by miguelsousa**
These changes will reduce the CFF table a bit.

### CODE REVIEW

**Comment by anthrotype** [comment]
Thanks Miguel! Do we support all the type2 drawing operators with this?

**Comment by miguelsousa** [comment]
No, not all of them. Some operators such as `rcurveline` are a combination of two or more segments. Supporting those would make the pen unnecessarily complex.
I think the pen now supports all the Type2 drawing operators that make sense in the context of a pen. The remaining operators, as well as optimizations (such as combining consecutive moveTos and curveTos), can be implemented during subroutinization.

**Comment by anthrotype** [comment]
I see. Well, this is definitely an improvement so we shall merge it. However, I think it still would be good to eventually support also the operators that combine multiple segments in this pen. We would just have to collect the current path's coordinates and "flush" them into the `self._program` only when `_closePath` or `_endPath` are called.

**Comment by anthrotype** [comment]
The line 119 is not covered by the tests:
https://codecov.io/gh/fonttools/fonttools/commit/70c695f8f69e614a097a54fbf8483392da9fab95

This is in the `T2CharStringPen._relativeMoveTo` method, when dy == 0 and the `hmoveto` operator is used.

**Comment by miguelsousa** [comment]
> We would just have to collect the current path's coordinates and "flush" them into the `self._program` only when `_closePath` or `_endPath` are called.

Yeah, that may be a way to do it, now that you mentioned it. I shall try it at a later date. But first I'll probably attempt to hook up the psOperatorSpecializer that Behdad referenced at #403 to the pen.

**Comment by behdad** [comment]
Thanks Miguel.  I checked your code.  It's definitely a good start.  It would be trivial to combine subsequent operators of the same kind.  Maybe I do that.

I think we should remove the RelativeCoordinatePen() and simplify the code a bit first.  It's more complex than it has to be.

**Comment by miguelsousa** [comment]
Yeah, I never quite understood the benefits of the RelativeCoordinatePen, so I left it alone.

**Pull request merged**
