### PR TITLE
Add SVGPen

### PR DESCRIPTION
**Pull request by khaledhosny**
Copied and slightly adapted from:
https://github.com/typesupply/ufo2svg/blob/master/Lib/ufo2svg/svgPathPen.py

### CODE REVIEW

**Comment by behdad** [comment]
Nice!

**Comment by anthrotype** [comment]
We shall add some round trip tests later

**Comment by benkiel** [comment]
Would it be better to add these sorts of things to https://github.com/robofab-developers/fontPens so that they can be more easily shared?

**Comment by anthrotype** [comment]
@benkiel well, fonttools is an install requirement of fontPens, and most other font-related python tools, so as far as "can be more easily shared", putting stuff in fonttools gains the most in terms of share-ability. 

I think fontPens is a good place for the robofab-like "point" pens (it's in fact a copy of the old robofab pens package), while fontTools.pens can keep its "segment" pens, at least for time being.

**Comment by justvanrossum** [comment]
@anthrotype, I understand what you mean, but we're seeing a fairly arbitrary divide between `fontTools.pens` and `fontPens` now.

**Pull request merged**
