### PR TITLE
[varLib.interpolate_layout] Tests for GPOS LookupType 1 and LookupType 2 specific pairs

### PR DESCRIPTION
**Pull request by miguelsousa**
The failures are due to XML round-tripping mismatches: `<Coverage Format="1">` vs. `<Coverage>`.
Cosimo, please do your magic. I believe the TTX result files are correct. Thanks!

### CODE REVIEW

**Comment by anthrotype** [comment]
The `fontTools.varLib.merger` is not setting the `Format` attribute of PairPos `Coverage`.
This is only calculated upon compiling in the `otTables.Coverage.preWrite` method.
I'm not quite sure how to solve that..
 
```
--- /Users/cosimolupo/Documents/Github/fonttools/Tests/varLib/data/test_results/InterpolateLayoutGPOS_2_spec_diff.ttx
+++ /var/folders/jb/rjz76yw92w7144mwqg119jnm0000gn/T/tmpxz_wwzk3/tmp1.ttx
@@ -34,7 +34,7 @@
         <LookupFlag value="0"/>
         <!-- SubTableCount=1 -->
         <PairPos index="0" Format="1">
-          <Coverage Format="1">
+          <Coverage>
             <Glyph value="A"/>
           </Coverage>
           <ValueFormat1 value="4"/>
```

**Comment by anthrotype** [comment]
@behdad said is going to fix this up

**Comment by behdad** [comment]
Done.

**Comment by miguelsousa** [comment]
Thanks.

**Pull request merged**
