### PR TITLE
[varLib.models] Generate narrower tents

### PR DESCRIPTION
**Pull request by behdad**
Based on https://github.com/fonttools/fonttools/pull/2218
but modify the general solver instead.

### CODE REVIEW

**Comment by behdad** [comment]
@justvanrossum please test this.  You can test the before/after by invoking:
```
./fonttools varLib.models -d file.designspace
```

Thanks.

**Comment by justvanrossum** [comment]
I tried with the test data from my PR: works for me!

```python
from fontTools.varLib.models import VariationModel


testData = [
    (
        [
            {},
            {"foo": 0.25},
            {"foo": 0.5},
            {"foo": 0.75},
            {"foo": 1.0},
            {"bar": 0.25},
            {"bar": 0.75},
            {"bar": 1.0},
        ],
        None,
        False,
        [
            {},
            {"bar": 0.25},
            {"bar": 0.75},
            {"bar": 1.0},
            {"foo": 0.25},
            {"foo": 0.5},
            {"foo": 0.75},
            {"foo": 1.0},
        ],
        [
            {},
            {"bar": (0, 0.25, 1.0)},
            {"bar": (0.25, 0.75, 1.0)},
            {"bar": (0.75, 1.0, 1.0)},
            {"foo": (0, 0.25, 1.0)},
            {"foo": (0.25, 0.5, 1.0)},
            {"foo": (0.5, 0.75, 1.0)},
            {"foo": (0.75, 1.0, 1.0)},
        ],
        [
            {},
            {0: 1.0},
            {0: 1.0, 1: 0.3333333333333333},
            {0: 1.0},
            {0: 1.0},
            {0: 1.0, 4: 0.6666666666666666},
            {0: 1.0, 4: 0.3333333333333333, 5: 0.5},
            {0: 1.0},
        ],
    ),
    (
        [
            {},
            {"foo": 0.25},
            {"foo": 0.5},
            {"foo": 0.75},
            {"foo": 1.0},
            {"bar": 0.25},
            {"bar": 0.75},
            {"bar": 1.0},
        ],
        None,
        True,
        [
            {},
            {"bar": 0.25},
            {"bar": 0.75},
            {"bar": 1.0},
            {"foo": 0.25},
            {"foo": 0.5},
            {"foo": 0.75},
            {"foo": 1.0},
        ],
        [
            {},
            {"bar": (0, 0.25, 0.75)},
            {"bar": (0.25, 0.75, 1.0)},
            {"bar": (0.75, 1.0, 1.0)},
            {"foo": (0, 0.25, 0.5)},
            {"foo": (0.25, 0.5, 0.75)},
            {"foo": (0.5, 0.75, 1.0)},
            {"foo": (0.75, 1.0, 1.0)},
        ],
        [
            {},
            {0: 1.0},
            {0: 1.0},
            {0: 1.0},
            {0: 1.0},
            {0: 1.0},
            {0: 1.0},
            {0: 1.0},
        ],
    ),
]


for locations, axisOrder, simple, sortedLocs, supports, deltaWeights in testData:
    model = VariationModel(locations, axisOrder=axisOrder)
    if simple:
        print("prints False before this PR, True after:")
    else:
        print("prints True before this PR, False after:")
    print(model.supports == supports)
```

**Comment by behdad** [comment]
There was a bug that I just fixed.

The test failures make me a bit suspicious. But yeah, my testing also suggests this is working.

Before:
```
$ ./fonttools varLib.models -l 0 1 2 3 4
Sorted locations:
[{}, {'A': 1.0}, {'A': 2.0}, {'A': 3.0}, {'A': 4.0}]
Supports:
[{},
 {'A': (0, 1.0, 4.0)},
 {'A': (1.0, 2.0, 4.0)},
 {'A': (2.0, 3.0, 4.0)},
 {'A': (3.0, 4.0, 4.0)}]
```
After:
```
$ ./fonttools varLib.models -l 0 1 2 3 4
Sorted locations:
[{}, {'A': 1.0}, {'A': 2.0}, {'A': 3.0}, {'A': 4.0}]
Supports:
[{},
 {'A': (0.0, 1.0, 2.0)},
 {'A': (1.0, 2.0, 3.0)},
 {'A': (2.0, 3.0, 4.0)},
 {'A': (3.0, 4.0, 4.0)}]
```

**Comment by behdad** [comment]
I fixed it I think. There's still 3 failures though, which I think need rebasing expectations.

**Comment by behdad** [comment]
@justvanrossum I've updated the tests now. This is ready I think.

**Comment by justvanrossum** [comment]
Tempted to say "LGTM", but TBH I find it hard to judge. Is test coverage extensive enough that we can be fairly confident this won't cause regressions?

**Review by anthrotype — APPROVED** [review]
LGTM

@behdad could you also add the test data from @justvanrossum's PR? https://github.com/fonttools/fonttools/pull/2218/files

**Comment by behdad** [comment]
> LGTM
> 
> @behdad could you also add the test data from @justvanrossum's PR? https://github.com/fonttools/fonttools/pull/2218/files

Done.

**Pull request merged**
