### PR TITLE
Set up Windows CI on Travis

### PR DESCRIPTION
**Pull request by anthrotype**
let's see how it works
https://blog.travis-ci.com/2018-10-11-windows-early-release

### CODE REVIEW

**Comment by anthrotype** [comment]
also, the Travis windows builds seem to be taking much longer than Appveyor's.
maybe it's a bit too early for this.

**Comment by behdad** [comment]
Oooh. Can someone do for HarfBuzz please? @ebraminio @khaledhosny

**Comment by anthrotype** [comment]
Azure Pipelines also supports all the three desktop platforms in the same CI and integrates well with GitHub. It's worth a try
also see https://medium.com/@anthonypjshaw/azure-pipelines-with-python-by-example-aa65f4070634

**Comment by anthrotype** [comment]
Github Actions also supports CI/CD for all three major OSes (and I believe it is also powered by Azure) and integrates naturally with Github's UI. I'll see if I can switch to that instead.
https://help.github.com/en/github/automating-your-workflow-with-github-actions/about-github-actions

**Pull request closed without merging**
