### PR TITLE
Small docs cleanups

### PR DESCRIPTION
**Pull request by n8willis**
These are pretty minor, but need to come before some reorg work on the autodoc configuration.

It does make a change to docs-requirements.txt, as described in #3606, which I think is necessary for the time being. I can only debug the output locally as long as the RTD theme is broken. I think a fix to the theme package is imminent, though.

### CODE REVIEW

**Comment by n8willis** [comment]
I'm not clear what the linter is unhappy with [here](https://github.com/fonttools/fonttools/actions/runs/10474434543/job/29008694193?pr=3611).

**Comment by behdad** [comment]
> I'm not clear what the linter is unhappy with [here](https://github.com/fonttools/fonttools/actions/runs/10474434543/job/29008694193?pr=3611).

Run `black fonttools/fonttools/Doc/source/conf.py`

**Comment by behdad** [comment]
LGTM but I'm no expert in the docs. Perhaps @anthrotype or @justvanrossum set this up?

**Comment by anthrotype** [comment]
> Perhaps anthrotype or justvanrossum set this up?

I believe @chrissimpkins did

Thanks @n8willis, I may take a look at this later but do not wait for my LGTM

**Comment by n8willis** [comment]
Also, if you're cool with me merging in small stuff, like stuff that doesn't extend outside the `Doc` subdirectory, I can save review-requests for things that alter or add content.....

**Review by anthrotype — APPROVED** [review]

**Pull request merged**
