### PR TITLE
[tfmLib] New library for reading TFM files

### LINKED ISSUE #2352: TFM parsing module?
I needed to parse dome TFM (TeX Font Metrics) files for a project, and I ended up writing a TFM parser (probably 80% complete, but I only tested it on a handful of files so far).

Since I’m eternally cursed with having to deal with such legacy files, I was wondering if it makes sense to add it to FontTools? I’m asking first because I know there were suggestions to drop parsers for legacy font formats before (t1Lib and afmLib I think), so I don’t want to spend work to find out the module is unwelcome here.

### PR DESCRIPTION
**Pull request by khaledhosny**
New library for reading TeX Font Metrics files. Does not support writing them back.

Fixes #2352

### CODE REVIEW

**Review by anthrotype — APPROVED** [review]
LGTM, thanks!

**Comment by anthrotype** [comment]
@khaledhosny I'm planning to cut a new release today, is it ok if I merge this?

**Comment by khaledhosny** [comment]
I was waiting for another reviewer, but if you are happy with it I’m happy. It already does what I need.

**Comment by anthrotype** [comment]
I only reviewed superficially as I don't know the details of TeX font metric data. Do you have in mind anyone who do and can review it? Otherwise, we take you as the ultimate "expert" and if issues arise we'll fix as we go along

**Comment by khaledhosny** [comment]
Lets just merge.

**Pull request merged**
