### PR TITLE
[feaLib] Allow deleting glyphs

### PR DESCRIPTION
**Pull request by simoncozens**
Support "sub A by NULL;" as described in https://github.com/adobe-type-tools/afdko/issues/1234 and implemented in AFDKO as https://github.com/adobe-type-tools/afdko/pull/1251

### CODE REVIEW

**Review by anthrotype — APPROVED** [review]
LGTM, thanks Simon!

**Comment by anthrotype** [comment]
(btw, that `parse_substitute_` method is 166 lines long.. one day maybe we should split it up into more manageable chunks)

**Comment by ctrlcctrlv** [comment]
# :eyes: 

dude…you can delete glyphs in OT Layout?

cool…wow. This makes a lot of hacks I've considered but then gave up on possible.

**Comment by justvanrossum** [comment]
See also https://github.com/MicrosoftDocs/typography-issues/issues/673

**Pull request merged**
