### PR TITLE
[feaLib] Test that G* table compilation does not change data

### PR DESCRIPTION
**Pull request by madig**
Continuation of https://github.com/fonttools/fonttools/pull/2229.

@behdad

### CODE REVIEW

**Comment by madig** [comment]
It's all missing `format` attributes 🤔

**Comment by madig** [comment]
I'm lost. Setting e.g. `self.Format = 1` in `def buildCoverage` in otlLib/builder.py has no effect on e.g. the TTX diff for `BuilderTest.test_FeatureFile_AlternateChained`.

**Comment by behdad** [comment]
This has some history. I'll type in a few hours.

**Comment by behdad** [comment]
> I'm lost. Setting e.g. `self.Format = 1` in `def buildCoverage` in otlLib/builder.py has no effect on e.g. the TTX diff for `BuilderTest.test_FeatureFile_AlternateChained`:

I'm not sure what you mean by this.

But this is why this thing is happening. For GSUB/GPOS types `Coverage`, `ClassDef`, `SingleSubst`, `AlternateSubst`, and `LigatureSubst`, ttLib has code in `otTables.py` to unify their multiple different formats into a unified Python API.

So naturally, the above code should also remove the `.Format` attribute, since it's already handled out. However, it wasn't done that way and the Format was dangling around in the objects loaded from binary. The Format is recomputed at compile time, depending on glyph order and the contents of the object. So the old dangling .Format is ignored. It has no purpose.

So when I forked fonttools, one of the things I did was to remove Format attribute from those structs. That was in 2013:

  https://github.com/fonttools/fonttools/commit/e93e29125f6c88a352e15b4d7732fc94a6402548

That caused a breakage in Compositor. While that was happening, feaLib was also developed. Issues around the .Format attribute popped up there; that's 2015:

  https://github.com/robotools/compositor/issues/7
  https://github.com/fonttools/fonttools/issues/475

In 2016, after I managed to get @justvanrossum's attention and we all started working on the same codebase, this Format change remained a pet peeve of his, and a few others also fought hard for the Format to come back. So I conceded:

  https://github.com/fonttools/fonttools/issues/92#issuecomment-199153825

Since then, it has been a routine pain point, because we can't roundtrip test GSUB/GPOS exactly as you are hitting with this change :(. I've even had to put hacks in just to make it bearable:

https://github.com/fonttools/fonttools/commit/fb0c60cd2ce68df546ea2887946bc7f97bbb6921
https://github.com/fonttools/fonttools/commit/479b52e13dbe6b7395bc652aa92d6481824d67b7
https://github.com/fonttools/fonttools/pull/878

Now, I remember a couple of years ago @justvanrossum commented on an issue saying he has since started to see things more the way I was seeing. So I wonder if it's time to reconsider the issue. Not being able to test that saving to binary and back produces the same objects makes it really hard to have confidence in the objects we build, which indeed makes saving to binary and loading a necessary "normalization" step as was found in ufo2ft.  To fix it, we need to make roundtrip-testing possible first.

HTH

**Comment by justvanrossum** [comment]
> So I wonder if it's time to reconsider the issue

If there's a general consensus that the Format field has no added value and only gets in the way, I will no longer insist on keeping it.

(Out of curiosity: @simoncozens recently improved compilation of certain GPOS subtables tables considerably, by compiling to the most efficient Format for the given data. Would discovering this and fixing that have been harder if the ttx hadn't contained the Format field, or would it not have made a difference? Would love to hear your opinion.)

**Comment by madig** [comment]
Oof, sounds like an epic refactoring if we want to make it possible to test roundtrips?

How to proceed here?

**Comment by behdad** [comment]
> If there's a general consensus that the Format field has no added value and only gets in the way, I will no longer insist on keeping it.

Thanks.  @anthrotype / @madig can you cherry-pick / adapt https://github.com/fonttools/fonttools/commit/e93e29125f6c88a352e15b4d7732fc94a6402548

> (Out of curiosity: @simoncozens recently improved compilation of certain GPOS subtables tables considerably, by compiling to the most efficient Format for the given data. Would discovering this and fixing that have been harder if the ttx hadn't contained the Format field, or would it not have made a difference? Would love to hear your opinion.)

Not really. For the structs that ttLib is presenting a higher-level API (Coverage, ClassDef, SingleSubst, AlternateSubst, and LigatureSubst), the ttLib compiler already picks the optimal format. Simon implemented that for other tables, namely the (Chain)Context{Subst,Pos}. Basically, for Coverage, ClassDef, SingleSubst, AlternateSubst, and LigatureSubst, you implemented otlLib.builder functionality right in the ttLib compiler.

**Comment by behdad** [comment]
> Thanks. @anthrotype / @madig can you cherry-pick / adapt [e93e291](https://github.com/fonttools/fonttools/commit/e93e29125f6c88a352e15b4d7732fc94a6402548)


I'm working on this.

**Comment by behdad** [comment]
> Oof, sounds like an epic refactoring if we want to make it possible to test roundtrips?

Wasn't too bad. Done: https://github.com/fonttools/fonttools/pull/2238

**Comment by behdad** [comment]
I've rebased this now. Let's see test fails. I will fix the ValueRecord failures in https://github.com/fonttools/fonttools/pull/2237/files

**Comment by behdad** [comment]
Humm. I'm not sure why the tests are passing without https://github.com/fonttools/fonttools/pull/2237

**Comment by anthrotype** [comment]
> I'm not sure why the tests are passing without #2237

because we had committed the (wrong) expected test result, which that PR fixes

**Comment by behdad** [comment]
> > I'm not sure why the tests are passing without #2237
> 
> because we had committed the (wrong) expected test result, which that PR fixes

But why doesn't going to binary and back catch that?

**Comment by anthrotype** [comment]
the test_buildPairPosGlyphsSubtable is not affected by compiling to binary, it only tests (via getXML) straight after built

**Review by anthrotype — APPROVED** [review]

**Pull request merged**
