### PR TITLE
Designspace lib improvements

### PR DESCRIPTION
**Pull request by behdad**
Adds a roundtripper, and fixes https://github.com/fonttools/fonttools/issues/3435

### CODE REVIEW

**Comment by behdad** [comment]
I tried updating the spec, but just the XML part. Looks like `AxisMappingDescriptor` is not in `python.rst` anyway.

**Comment by davelab6** [comment]
@behdad is this ready to review and merge?

**Review by anthrotype — APPROVED** [review]
LGTM

only nit: I don't see the current tests exercising the new mutliple `<mappings>` elements, you might want to add an explicit test for those

**Comment by behdad** [comment]
I'll update the tests when on laptop.

**Pull request merged**
