### PR TITLE
[varLib] "Fix" cython iup issue?

### PR DESCRIPTION
**Pull request by cmyr**
See #3703.

In some cases we were seeing different output from iup depending on whether or not we were running cython code.

I've tracked this particular issue down to the line that is changed in this diff, and the change introduced in this diff does (locally, for me, on one machine with one architecture and one compiler) seem to suppress the problem.

However... it feels pretty bad??

I'm not sure how motivated I am to try and generate a proper minimal test case and try to get this fixed upstream. I guess I'm.. medium motivated? But at the very least it would be nice to figure out a more robust way to prevent this optimization from happening, and at the very _very_ least it would be nice to figure out away to test this.

The solution I was hoping for was some way to write some actual hand-written C so we could have finer-grained control over what's going on, and use that just for this one little bit of arithmetic, but I didn't see an easy way to do that.

In any case, I'm going to PR this as a conversation starter at least, and we can try to figure out what the best solution looks like?

### CODE REVIEW

**Comment by behdad** [comment]
Ah, so it was a fused mul-add after all! Yeah the best thing would be to add a compiler barrier there. I'll take a look later, I don't think it's possible. The nudge forces this to go to a Python object and back, which is annoying.

**Comment by behdad** [comment]
Seems like verbatim C can be added:
https://stackoverflow.com/questions/57965780/cython-openmp-single-barrier

**Comment by behdad** [comment]
I'm working on it...

**Comment by cmyr** [comment]
> Ah, so it was a fused mul-add after all! Yeah the best thing would be to add a compiler barrier there. I'll take a look later, I don't think it's possible. The nudge forces this to go to a Python object and back, which is annoying.

I looked at the generated C and it doesn't seem to, though? Everything is a `double`:

```
  079:                 # Interpolate
+080:                 nudge = (x - x1) * scale
      /*else*/ {
        __pyx_v_nudge = ((__pyx_v_x - __pyx_v_x1) * __pyx_v_scale);
+081:                 d = d1 + nudge
        __pyx_v_d = (__pyx_v_d1 + __pyx_v_nudge);
      }
      __pyx_L10:;
```

and so I'm surprised this breaks the optimization? Initially I had a `print` statement that printed intermediate results, but then I saw that it was working even without that..

**Comment by behdad** [comment]
Ugh. I'm doing some refactoring and now gcc/clang hang on compiling the modules!

**Comment by cmyr** [comment]
Updated this to explain what's going on in a comment, and add a link to godbolt showing the optimization on & off. It shouldn't _hurt_ to merge...

**Comment by behdad** [comment]
LGTM. Thanks.

**Pull request merged**
