### PR TITLE
[varLib.avar] Reconstruct mappings from binary

### PR DESCRIPTION
**Pull request by behdad**
https://github.com/Lorp/fencer/issues/25

### CODE REVIEW

**Comment by behdad** [comment]
Just wrote this to @Lorp:

So here's the thing:
lemme see how to explain it.
Everything in normalized numbers.
Imagine a master at wght=1. driving stem=1
And wdth=1 also driving stem=1
And then a middle master at wght=.5,wdth=.5 with start/end's at 0,1 on both axes.
We generate a corner for wght=1,wdth=1
Then we sample the varStore at that point, for stem axis. We would get 2.
Then we clamp it to 1 and that changes the geometry.
I think we should NOT clamp.
And then when we drop "unnecessary" poles, the problem will probably go away.
That's my current thinking.

**Comment by behdad** [comment]
Run the tool like:
```
fonttools varLib.avar RobotoFlex-avar2.ttf
```
It will write the avar1 segments and avar2 mappings to console.

**Comment by behdad** [comment]
The tricky part: removing unnecessary pins, is untested by me as I don't have a font for it right now. But otherwise I think this is ready for review.

**Comment by behdad** [comment]
With tests now for the location-pruning. My confidence is rather high now.

**Comment by behdad** [comment]
Next step, I suppose, is to print out .designspace-like output.

**Comment by behdad** [comment]
Here's it in action. With Raqq's build, the mappings:
https://github.com/aliftype/raqq/blob/8d8ca9e4e41ac660113204fd82fc9029a06335a8/scripts/build.py#L876-L885
```
mappings = [
        [{"Justification": -100}, {"Spacing": -100, "Mashq": 0}],
        [{"Justification": -50}, {"Spacing": 0, "Mashq": 0}],
        [{"Justification": 0}, {"Spacing": 0, "Mashq": 10}],
        [{"Justification": 90}, {"Spacing": 0, "Mashq": 100}],
        [{"Justification": 100}, {"Spacing": 125, "Mashq": 100}],
    ]
```
the tool output:
```
$ ./fonttools varLib.avar Raqq.ttf 
{}
[({'jstf': -50.0}, {'MSHQ': 0.0}),
 ({'jstf': -100.0}, {'MSHQ': 0.0, 'SPAC': -100.0}),
 ({'jstf': 90.00244140625}, {'MSHQ': 100.0}),
 ({'jstf': 100.0}, {'MSHQ': 100.0, 'SPAC': 125.0})]
4 mappings
```

**Comment by behdad** [comment]
I added a roundtrip test, and it's failing, because:

https://github.com/fonttools/fonttools/pull/3601

Or we can change the tests.

**Comment by behdad** [comment]
With https://github.com/fonttools/fonttools/pull/3601 fixed, this is now ready.

@Lorp how does it look to you?
@justvanrossum @anthrotype Can you take a look possibly? Thanks.

**Comment by behdad** [comment]
I'll make it print .designspace snippet instead.

**Comment by behdad** [comment]
> I'll make it print .designspace snippet instead.

Done. At some point we'll add `--output-file` etc. But I think this can be merged now.

**Comment by behdad** [comment]
Since this just adds new functionality to an obscure module (`varLib.avar`), I'm leaning towards merging it if no one wants to review. Thanks.

**Review by anthrotype — APPROVED** [review]

**Pull request merged**
