### PR TITLE
VarLibMergeError.stack is a list of str, not a str

### PR DESCRIPTION
**Pull request by anthrotype**
Fixes https://github.com/googlefonts/fontmake/issues/766

### CODE REVIEW

**Comment by simoncozens** [comment]
Looks good; yes, I missed that one. Thanks!

**Review by simoncozens — APPROVED** [review]

**Comment by madig** [comment]
The line may need further change; I still get a faulty exception. In the linked issue when I change it to

`raise ShouldBeConstant(merger=merger, expected=allValues[0], got=lst, stack=["."+k])`

I get the following error:

```
fontmake: Error: In '..\..\..\..\Users\nikolaus.waxweiler\AppData\Local\Temp\Kumbh_Sans_Sources\DesignSpace-UFO\KumbhSans_Var_35.designspace': Generating fonts from Designspace failed: 

Couldn't merge the fonts, because some values were different, but should have
been the same. This happened while performing the following operation:
GDEF.table.GlyphClassDef.hbar

The problem is likely to be in Kumbh Sans Black Regular:
Expected to see .hbar==3, instead saw {'S': 1, 'g': 1, 'e': 1, 's': 1, 'U': 1, 'a': 1, 'h': 1, 'n': 1, 'd': 1, 'o': 1, 'i': 1, 'H': 1, 'N': 1, 'D': 1, 'C': 1, 'E': 1, 'I': 1, 'L': 1, 'l': 1, 'G': 1, 'J': 1, 'j': 1, 'c': 1, 't': 1, 'k': 1, 'w': 1, 'u': 1, 'y': 1, 'z': 1, 'r': 1, 'T': 1, 'R': 1, 'Y': 1, 'Z': 1, 'quoteleft': 1, 'commaaccent': 1, 'Eth': 1, 'Idotaccent': 1, 'Lcaron': 1, 'lcaron': 1, 'Ldot': 1, 'Adieresis': 1, 'Aring': 1, 'Egrave': 1, 'Eacute': 1, 'Ecircumflex': 1, 'Edieresis': 1, 'Igrave': 1, 'Iacute': 1, 'Icircumflex': 1, 'Idieresis': 1, 'Ograve': 1, 'Oacute': 1, 'Ocircumflex': 1, 'Odieresis': 1, 'Ugrave': 1, 'Uacute': 1, 'Ucircumflex': 1, 'Udieresis': 1, 'Yacute': 1, 'ograve': 1, 'ocircumflex': 1, 'odieresis': 1, 'yacute': 1, 'ydieresis': 1, 'Amacron': 1, 'Cacute': 1, 'cacute': 1, 'Ccircumflex': 1, 'ccircumflex': 1, 'Cdotaccent': 1, 'cdotaccent': 
1, 'Ccaron': 1, 'ccaron': 1, 'Dcaron': 1, 'Emacron': 1, 'Ebreve': 1, 'Hcircumflex': 1, 'hcircumflex': 1, 'Imacron': 1, 'IJ': 1, 'Jcircumflex': 1, 'uni0137': 1, 'Lacute': 1, 'lacute': 1, 'uni013B': 1, 'uni013C': 1, 'Tcaron': 1, 'tcaron': 1, 'Umacron': 1, 'Ubreve': 1, 'Uring': 1, 'Uhungarumlaut': 1, 'Wcircumflex': 1, 'wcircumflex': 1, 'Ycircumflex': 1, 'ycircumflex': 1, 'Ydieresis': 1, 'Zacute': 1, 'zacute': 1, 'Zdotaccent': 1, 'zdotaccent': 1, 'Zcaron': 1, 'zcaron': 1, 'uni021B': 1, 'Nacute': 1, 'uni0145': 1, 'Ncaron': 1, 'Omacron': 1, 'omacron': 1, 'Obreve': 1, 'obreve': 1, 'Wgrave': 1, 'wgrave': 1, 'Wacute': 1, 'wacute': 1, 'Wdieresis': 1, 'wdieresis': 1, 'Kcommaaccent': 1, 'Dcroat': 1, 'oslash': 1, 'ij': 1, 'kgreenlandic': 1, 'Lslash': 1, 'lslash': 1, 'OE': 1, 'oe': 1, 'ohungarumlaut': 1, 'tbar': 1, 'dotlessj': 1, 'oacute': 1, 'trademark': 1, 'fi': 1, 'fl': 1, 'f_f_i': 1, 'f_f_l': 1, 'longs_t': 1, 'ldot': 1, 'Tcommaaccent': 1, 'Ccedilla': 1, 'Ntilde': 1, 'agrave': 1, 'aacute': 1, 'acircumflex': 1, 'atilde': 1, 'adieresis': 1, 'aring': 1, 'ccedilla': 1, 'egrave': 1, 'eacute': 1, 'ecircumflex': 1, 'edieresis': 1, 'ntilde': 1, 'otilde': 1, 'ugrave': 1, 'uacute': 1, 'ucircumflex': 1, 'udieresis': 1, 'amacron': 1, 'abreve': 1, 'aogonek': 1, 'dcaron': 1, 'dcroat': 1, 'emacron': 1, 'ebreve': 1, 'Edotaccent': 1, 'edotaccent': 1, 'eogonek': 1, 'Ecaron': 1, 'ecaron': 1, 'Eogonek': 1, 'Gcircumflex': 1, 'gcircumflex': 1, 'Gbreve': 1, 'gbreve': 1, 'Gdotaccent': 1, 'gdotaccent': 1, 'Gcommaaccent': 1, 'gcommaaccent': 1, 'Itilde': 1, 'Iogonek': 1, 'nacute': 1, 'ncommaaccent': 1, 'ncaron': 1, 'napostrophe': 1, 'Racute': 1, 'racute': 1, 
'Rcommaaccent': 1, 'rcommaaccent': 1, 'Rcaron': 1, 'rcaron': 1, 'Sacute': 1, 'sacute': 1, 'Scircumflex': 1, 'scircumflex': 1, 'Scedilla': 1, 'scedilla': 1, 'Scaron': 1, 'scaron': 1, 'Tcedilla': 
1, 'tcedilla': 1, 'Utilde': 1, 'utilde': 1, 'umacron': 1, 'ubreve': 1, 'uring': 1, 'uhungarumlaut': 1, 'Uogonek': 1, 'uogonek': 1, 'Scommaaccent': 1, 'scommaaccent': 1, 'iogonek': 1, 'cedilla': 
3, 'ogonek': 3, 'grave': 3, 'tilde': 3, 'circumflex': 3, 'acute': 3, 'caron': 3, 'macron': 3, 'dieresis': 3, 'breve': 3, 'ring': 3, 'dotaccent': 3, 'hungarumlaut': 3, 'iacute': 3, 'icircumflex': 3, 'idieresis': 3, 'igrave': 3, 'Hbar': 3, 'hbar': 3, 'jcircumflex': 3, 'Tbar': 3}
```

which, uh, doesn't make sense to me entirely?! so what should the `merger` argument be?

**Comment by simoncozens** [comment]
merger should be `self`, i.e. the varLib.merger object.

**Comment by madig** [comment]
Yes but then I get another exception saying that merger.ttfs does not exist.

**Pull request merged**
