### PR TITLE
make function posix(path) in designspaceLib work with Windows UNC path

### PR DESCRIPTION
**Pull request by Eigi**
fix for #2299

### CODE REVIEW

**Comment by anthrotype** [comment]
can you elaborate a bit on how you use UNC paths in designspace files?
According to the spec, the `filename` attribute should contain only relative paths, and as far as I understand these UNC paths are by definition absolute paths.

**Comment by Eigi** [comment]
Yes, the filename attribute is relative, but the path attribute of the designSpaceDocument itself is absolut. And the path attribute of sources and instances is calculated as absolute paths form the respective filename and the path of the designSpaceDocument. The error occurs if the designSpaceDocument is loaded from a server with an UNC path. As a result the sources can't be loaded even if they are in the same folder as the designSpaceDocument. This is the standard situation in my production environment.

**Comment by anthrotype** [comment]
i see. But are you sure that inserting two leading _forward_ slashes will still make it work as a UNC path? Don't the latter always require two backslashes? /cc @madig

**Comment by Eigi** [comment]
two leading forward slashes work. and we have one forward slash in the mount part of the UNC path anyway, between server and share. `//server/share/folder/filename`.

**Comment by anthrotype** [comment]
ok, let's merge it then

**Pull request merged**
