### PR TITLE
[avar2] Implement avar2 support in ttGlyphSet.

### PR DESCRIPTION
**Pull request by behdad**
Implementing avar2 support in ttGlyphSet

Fixes https://github.com/fonttools/fonttools/issues/3469

### CODE REVIEW

**Comment by behdad** [comment]
This seems to be working now!  You can grab avar2 fonts from:

https://drive.google.com/drive/folders/1OjZFadiSKwzPnGWWCmNwscJN8bsjfqR0

**Comment by behdad** [comment]
Will work on other modules too. But this is ready. We don't have subsetter for it though, so can't produce a test right now.

**Comment by behdad** [comment]
> We don't have subsetter for it though

Nevermind. Subsetter doesn't change avar. Instancer does.

**Comment by behdad** [comment]
Test added!

**Comment by behdad** [comment]
Humm. Let's merge this and continue on other modules separately. I see three modules that need updating:

  - varLib.instancer. The hardest. I have jotted some notes here:
    https://docs.google.com/document/d/14elERu9Y_umFMg_lxnw7qtpskNlFvKhVtg2RNQteOek/edit

  - varLib.interpolatable. Not exactly sure what needs to be done, but I'll take a look.

  - designspaceLib. Also hard, because it uses single-axis `map_forward` and `map_backward` a lot. In other word, some of the functions there need to be deprecated and cannot work in a avar2 model.

**Comment by behdad** [comment]
@justvanrossum Can I get a review from you please?

**Review by anthrotype — APPROVED** [review]
LGTM

**Comment by justvanrossum** [comment]
It works beautifully! Thank you so much. Playing with svgPathPen as you suggested.

For more thorough code reviewing I'd need more time, but since Cosimo approved, feel free to merge.

**Pull request merged**
