### PR TITLE
[maxp] Include 'maxComponentElements' in the table's recalculation

### PR DESCRIPTION
**Pull request by miguelsousa**

### CODE REVIEW

**Comment by anthrotype** [comment]
almost unbelievable how this went unnoticed for so long

**Comment by miguelsousa** [comment]
I'm wondering how many tests this change will break.

**Comment by anthrotype** [comment]
> I'm wondering how many tests this change will break.

you mean, _fix_ :wink:

**Comment by miguelsousa** [comment]
merge commit?

**Comment by anthrotype** [comment]
yes please

**Pull request merged**
