### PR TITLE
merge ufoLib into fontTools.ufoLib

### PR DESCRIPTION
**Pull request by anthrotype**
Part of #1095

### CODE REVIEW

**Comment by anthrotype** [comment]
basically, I fetched from the upstream ufoLib's remote, moved files to Lib/fontTools, then removed all duplicate files (setup.py, etc.), and finally used `git merge --allow-unrelated-histories` to merge all git history from one repository to the other.
It's a lot of history, but the most relevant commits are the ones following https://github.com/fonttools/fonttools/pull/1335/commits/49c7bd1e1d08500c6ddb783df3ae61184982d89d, which is the last commit from ufoLib/master.

**Comment by anthrotype** [comment]
I've laso copied the `*.rst` files from the ufoLib/Documentation to the Doc/sources/ufoLib subfolder, but didn't also copy the Sphinx setup, since there is #1333 pending which overlaps with this.

I reorganized a few modules and moved them in other places where they make more sense, but kept shims that re-export all the symbols from the old module location, to make the transition easier.
These are:

- `ufoLib.etree` => `fontTools.misc.etree`
- `ufoLib.plistlib` => `fontTools.misc.plistlib`
- `ufoLib.pointPen` => `fontTools.pens.pointPen`

Finally, I added `extras_require` to the setup.py script, to allow to specify the optional dependencies:
https://github.com/fonttools/fonttools/pull/1335/commits/783707644bfa0d92d924faea745e34f3c0555219

Currently, the optional dependencies are grouped under the following extras keys:
`ufo`, `woff`, `lxml`, `unicode`, `interpolatable`, `symfont`, `type1`
There is also a catch-all extra key, called simply `all`, that installs all the optional dependencies in one go.

Just a reminder: each of these strings can be added to the `pip install fonttools[...]` invocation (or when specifying fonttools as a dependency in one's setup.py). They go between the square brackets and are  separated by commas. E.g.:

`pip install fonttools[ufo,lxml,unicode]` will install fonttools plus all the optional dependencies needed to, in this case, read/write UFOs, using lxml (instead of ElementTree), and with unicodedata from current Unicode 11.

**Comment by anthrotype** [comment]
So, to make this clear, the core of fontTools (e.g. ttx, ttLib, etc.) stays dependency-free. But in order to use the new `fontTools.ufoLib`, one needs to install the `fs` module (aka pyfilesystem2), and the `enum34` backport only if running under python2.7.
This is all specified under the `[ufo]` extra requirement, and the user only needs to remember to type `pip install fonttools[ufo]` iff they want to read/write UFOs with fontTools. Otherwise nothing changes for them.

**Comment by chrissimpkins** [comment]
Will update #1333 with the new docs and rebase source (incl. setup.py) on your new version here.  We can add the ufo extras requirement to the RTD settings file so that all of those new dependencies are pulled for remote doc builds.

**Comment by anthrotype** [comment]
@chrissimpkins thanks. let's first merge this then you can rebase on master

**Comment by typesupply** [comment]
I will have time for a quick review mid-day tomorrow. Is that soon enough?

**Comment by anthrotype** [comment]
that's great, thank you :+1:

**Comment by anthrotype** [comment]
another legacy thing that I would love to get rid of, for the sake of consistency between lxml and ElementTree, is the custom xml declaration that uses double instead of single quotes.  Both lxml and ElementTree use single quotes:

```
<?xml version='1.0' encoding='UTF-8'?>
```

but in ufoLib we write it with double quotes because that's what it had always done.
This is the time to change these little annoying things.

**Comment by benkiel** [comment]
@anthrotype I'm ok changing it, it's a one-time break to everyone's git histories. @miguelsousa you ok with such a thing? I know it's super annoying, but....

**Comment by miguelsousa** [comment]
@anthrotype go ahead with all the cleanup/simplification/breakage. Now is the time.
After the merge, your UFO-breakage allowance will be freezed for 10 years 😄

**Comment by benkiel** [comment]
Congrats @anthrotype!

**Comment by anthrotype** [comment]
Thanks to all the ufoLib contributors!

**Pull request merged**
