### PR TITLE
Fix for #1985: ensure that the AxisNameID in the STAT table is > 255

### PR DESCRIPTION
**Pull request by justvanrossum**
Fix for #1985: ensure that the AxisNameID in the STAT table is not less than 256. This needed an additional argument to the addMultiLingualName() name table method.

### CODE REVIEW

**Comment by anthrotype** [comment]
Hm. If it's not a hard FAIL, maybe we can just live with the OTS warning and try to relax the STAT table spec to also allow AxisNameIDs <= 255 like AxisValues valueNameIDs are allowed to be?

**Comment by justvanrossum** [comment]
I need to apply the same logic to `_add_fvar` in `varLib`.

**Comment by justvanrossum** [comment]
I can't see a quick way to add an fvar test for this, though.

**Comment by anthrotype** [comment]
> I can't see a quick way to add an fvar test for this, though.

it's ok like that

**Comment by justvanrossum** [comment]
As mentioned in https://github.com/MicrosoftDocs/typography-issues/issues/433#issuecomment-640757610 there's another [restriction for named instances](https://docs.microsoft.com/en-us/typography/opentype/spec/fvar#instancerecord):

> The subfamilyNameID field provides a name ID that can be used to obtain strings from the 'name' table that can be treated as equivalent to name ID 17 (typographic subfamily) strings for the given instance. Values of 2 or 17 can be used; otherwise, values must be greater than 255 and less than 32768. The values 2 or 17 should only be used if the named instance corresponds to the font’s default instance.

I think the chance that this would accidentally be violated is tiny, and not worth checking for explicitly.

**Pull request merged**
