### PR TITLE
don't compute git version at runtime; bump version with custom 'release' command

### PR DESCRIPTION
**Pull request by anthrotype**
Following the discussion at #767 and the overall negative feedback about the versioneer.py approach for computing the package version string at import time through git, I decided to reverted those changes and go back to a static version string for the setup.py and fontTools.__init__.py files.

I'm still using the `bumpversion` tool to automate the process, and also created a custom setuptools command (`python setup.py release`) to bootstrap bumpversion and apply the version scheme.

Below is the docstring explaining how this works.

```
        """
	Tag a new release with a single command, using the 'bumpversion' tool
	to update all the version strings in the source code.
	The version scheme conforms to 'SemVer' and PEP 440 specifications.

	Firstly, the pre-release '.devN' suffix is dropped to signal that this is
	a stable release. If '--major' or '--minor' options are passed, the
	the first or second 'semver' digit is also incremented. Major is usually
	for backward-incompatible API changes, while minor is used when adding
	new backward-compatible functionalities. No options imply 'patch' or bug-fix
	release.

	A new header is also added to the changelog file ("NEWS"), containing the
	new version string and the current 'YYYY-MM-DD' date.

	All changes are committed, and an annotated git tag is generated. With the
	--sign option, the tag is GPG-signed with the user's default key.

	Finally, the 'patch' part of the version string is bumped again, and a
	pre-release suffix '.dev0' is appended to mark the opening of a new
	development cycle.

	Links:
	- http://semver.org/
	- https://www.python.org/dev/peps/pep-0440/
	- https://github.com/peritus/bumpversion
	"""
```

I would basically be the only user, but encourage others to have a look and give feedback if they like.

Thank you, and apologies for my obstinacy with this not-very-cool-but-somebody-has-to-do-it stuff.

### CODE REVIEW

**Comment by anthrotype** [comment]
(of course, I don't want to be the only user... that's why I tried to make it simple for others to use as well)

**Comment by justvanrossum** [comment]
Thanks so much for your continuous dedication and efforts! I'm very happy with this solution.

**Comment by anthrotype** [comment]
Cool, I'm happy you're happy! I'll use this shortly to tag a 3.3.1 release. Let's see if actually works.. ;)

**Comment by anthrotype** [comment]
yes, it worked!

These are the commands I run:

```shell
python setup.py release --sign
git push origin $(git describe --abbrev=0 --tags)
```

I didn't have the --sign option on by default, because it depends on having git properly configured for using a GPG signing key.
E.g. see https://help.github.com/articles/telling-git-about-your-gpg-key/

The second command simply pushes the current tag to the `origin` remote, which is fonttools/fonttools on my machine.

**Comment by anthrotype** [comment]
Actually the commands above only push the tag, but not the commits..
There should be an extra git push in between: 

```
python setup.py release --sign
git push origin master
git push origin $(git describe --abbrev=0 --tags)
```

I wish I could do `git push --follow-tags`, but that would also push along all my private tags (which we did for internal deployment).

**Pull request merged**
