### PR TITLE
Add fea generation support

### PR DESCRIPTION
**Pull request by mhosken**
This PR enables fonttools to generate fea syntax from a fea ast, as per issue #772. I notice that #479 is not ast based and simply generates text as it goes.

One calls asFea() on the output from a Parser().parse() and is returned a string containing the generated fea text.

At this point in the PR's history not all the tests are giving identical results. This is due to the following features not yet having been implemented:

- Ranges are expanded in the parser and not contracted in fea generation. This might be worked around by keeping a side copy of the original glyph list specification including ranges.
- nameid attributes are often defaulted and expanded in the parser. These are not defaulted out in the fea generation.

In order to get the tests to pass, many of them have been adjusted in layout and some keywords regularised. These need to be reviewed to ensure that the tests are still testing what the test was originally designed to test. A special comment can also be used to acknowledge different output from fea2fea for a test. E.g. feaLib/testdata/size.fea

### CODE REVIEW

**Comment by brawer** [comment]
Thank you, looks good to me! There’s a minor typo which I’ll fix myself.

**Comment by anthrotype** [comment]
wow this is huge! thanks a lot Martin! 💯 
I'm look forward to use this.

**Comment by twardoch** [comment]
cool!

**Comment by anthrotype** [comment]
I was wondering if instead of, or in addition to, `asFea()` methods, we could have `__str__` methods for each `ast` object, so one could do `str(something)` or `print(something)`.

**Pull request merged**
