### PR TITLE
[ttx] use GNU-style getopt to intermix options and positional arguments

### PR DESCRIPTION
**Pull request by anthrotype**
Fixes https://github.com/fonttools/fonttools/issues/3507

### CODE REVIEW

**Review by justvanrossum — APPROVED** [review]
Fantastic, great find, thanks!

**Comment by khaledhosny** [comment]
Best 4-char patch of the year.

**Comment by anthrotype** [comment]
I wonder why I'd never even realised that ttx had this sort of limitation, I guess I'm used to write the options first followed by the input file instead of the other way around

**Comment by khaledhosny** [comment]
I suffer from it probably every time I use ttx, but I have always accepted it as a fact of life!

**Pull request merged**
