### PR TITLE
[WIP] TTFont: Use mmap if possible

### PR DESCRIPTION
**Pull request by behdad**
As discussed here:
https://github.com/behdad/fonttools/issues/580#issuecomment-211110222

Before:
$ python -m timeit 'from fontTools.ttLib import TTFont; TTFont("sazanami-gothic.ttf")'
10 loops, best of 3: 66.9 msec per loop

After:
$ python -m timeit 'from fontTools.ttLib import TTFont; TTFont("sazanami-gothic.ttf")'
10000 loops, best of 3: 110 usec per loop

That's a 600x speedup!

Fixes https://github.com/behdad/fonttools/issues/482

HOWEVER, it reintroduces https://github.com/behdad/fonttools/issues/302
Or worse, we'll crash when overwriting:

$ cp Lobster.ttf t.ttf
$ ./ttx -o ./t.ttf ./t.ttf
Dumping "./t.ttf" to "./t.ttf"...
Dumping 'GlyphOrder' table...
Bus error (core dumped)

IMO we should fix this by changing both XML and font output routines to,
instead of calling open, use os.tmpfile(), create output in a new file
and then rename it to the final destination.  It has the benefit of not
leaving a half-written output file behind if an exception occurs.  The
tempfile.NamedTemporaryFile also comes handy.

While checking those out, tempfile.SpooledTemporaryFile also comes handy,
when it's available, to replace BytesIO in the following part of TTFont.save():

```
# write to a temporary stream to allow saving to unseekable streams
tmp = BytesIO()
```

Looks like we need to start misc.fileTools to abstract the details away.

### CODE REVIEW

**Comment by behdad** [comment]
This is not ready to be merged; uploaded for discussion.

That's enough playing with this issue instead of getting started on filing taxes...  @anthrotype Feel free to finish it!

**Comment by moyogo** [comment]
Wow! That’s impressive.

**Comment by justvanrossum** [comment]
I've never used the mmap module, but your timing example can't be right: mmap reads lazily, so your before and after test pretty much compare reading the entire file into memory vs. not reading the entire file into memory. A fair comparison would be to parse all glyph data after creating the TTFont().

**Comment by justvanrossum** [comment]
Also: it's a little (read: very) scary that mmap can cause a core dump...

**Comment by justvanrossum** [comment]
Ah ok, I think I was misunderstanding what you're trying to do. But I think the whole exercise is a little backwards, and your proposal to use temp files (so we can overwrite loaded fonts) is probably much better. (It would also solve #536.)

**Comment by behdad** [comment]
Right, the goal of this exercise was to make the font loading be lean again, like it used to be when we didn't read the whole file.  @justvanrossum you are right that when we do the temp file, then we can go back to not reading the font file at all, like before.  That said, mmap() is still a more efficient way than reading the file, so I suggest we keep this as well.  I know this is not common in Python, but since there is a mmap module we might as well use it, as it saves a copy.

**Comment by justvanrossum** [comment]
Not at all convinced of using mmap in this case. How much speed can be gained? Let's measure that. I doubt data copying and file io is contributing much to any lack of performance. mmap is less portable, and can cause core dumps (that's actually pretty disgusting all by itself). Remember, even a huge TTF is a small file by today's standards.

**Comment by anthrotype** [comment]
I haven't used mmap either, and would like to read a bit more about it.
As far as I understand, it uses the operating system's virtual memory to access the data on the filesystem directly. It feels a bit risky. Instead of making sys calls like open, read etc., it puts the file data into memory and allows one to directly manipulate that in memory.
I quite like the fact that it works the same as both a bytearray and a file object though. However, I see it has different interfaces for Unix and Windows. And It feels quite low-level in general... 😕

**Comment by justvanrossum** [comment]
Exactly. Btw. FontTools has never been about performance. It's about being flexible and reliable in accessng and manipulating font data. Sure, if things can be rewritten in a way that improves performance, great, but it should not make the code more complicated. Might as well rewrite the whole thing in C++ then, and that's not why we're here.

**Comment by behdad** [comment]
I don't insist in this going on.  Definitely not.  But want to share my perspective as well:

- HarfBuzz and FreeType both mmap() the font file and use it.  If they didn't, every app on an Android device would have consumed many megabytes more memory.

- I understand FontTools was not originally design for the kind of work that is latency-critical.  However, Google Fonts *is* using it to subset fonts on demand, and when I added the subset module two years ago, I significantly sped up many parts, most in loading.

I do want to measure this more as well.

**Comment by justvanrossum** [comment]
If the use of mmap can be abstract and reliable (no core dumps!) and portability isn't at stake, and brings us measurable advantages, then by all means, go ahead.

**Comment by anthrotype** [comment]
looks like mmap does not work with standard I/O streams:
http://stackoverflow.com/questions/6510819/using-mmap-with-popen

(we haven't implemented it yet, but I think it's nice if fonttools scripts could read/write from stdin/stdout -- binary data, not just text).

**Comment by behdad** [comment]
> (we haven't implemented it yet, but I think it's nice if fonttools scripts could read/write from stdin/stdout -- binary data, not just text).

That already works in my implementation.   It falls back to the code that was there before.

**Comment by brawer** [comment]
Can this be merged?

**Comment by brawer** [comment]
Ugh, I’ve pressed the “Update branch” button in GitHub, assuming this would rebase to master; instead, it merged master *into* the branch and now the branch is messed up.

Anyhow, what should be done with this pull request? Personally I don’t see any disadvantages with trying to mmap (and falling back to normal I/O in case of failure), as the pull request already does. So I think we should merge it. My only concern is what happens on Windows. @anthrotype, do you know what it would take to make this work on Windows? See the TODO in the code.

**Comment by behdad** [comment]
> Anyhow, what should be done with this pull request if it actually worked? Personally I don’t see disadvantages with trying to mmap (and falling back to normal file I/O in case of failure), like the pull request already does. So I think we should merge it. My only concern is what happens on Windows. @anthrotype, do you know what it would take to make this work on Windows? See the TODO in the code.

Windows is not a concern.  We either implement using mmap on Windows, or it will just fallback to non-mmap.

This cannot be merged yet however, as we need to clean up all places where we write to files to write to a temp file and rename it.  Right now, with the mmap branch, if source and destination of ttx are the same file, we crash.  That's not acceptable.

**Comment by behdad** [comment]
I still think this is a good idea, but closing since others don't :).

**Pull request closed without merging**
