### PR TITLE
Create renaming-glyphs.py

### LINKED ISSUE #149: [snippets] Renaming glyphs
For TrueType, something like this works:

``` python
    font = fontTools.ttLib.TTFont(inpath)
    glyphnames = font.getGlyphOrder()
        # Do the renaming in glyphnames...
    font = fontTools.ttLib.TTFont(inpath) # load again
    font.setGlyphOrder(glyphnames)
    post = font['post']
    font.save(outpath)
```

For cff, we need to set font['CFF '].cff.topDictIndex[0].charset, but also to remap font['CFF '].cff.topDictIndex[0].CharStrings as in https://github.com/behdad/fonttools/issues/147.

### PR DESCRIPTION
**Pull request by davelab6**
Closes #149

### CODE REVIEW

**Comment by miguelsousa** [comment]
@anthrotype merge?

**Comment by anthrotype** [comment]
No. It's missing imports and doesn't even run. I suggest you look at how ufo2ft does the glyph renaming here
https://github.com/googlei18n/ufo2ft/blob/2d42d89b41538acdd89e66faa6c7c475bbea52ff/Lib/ufo2ft/postProcessor.py#L28

**Comment by behdad** [comment]
Either finish or close.

**Comment by khaledhosny** [comment]
One year later… closing then (the issue is still open, though).

**Pull request closed without merging**
