### PR TITLE
[subset] Fix subsetting of variable fonts

### PR DESCRIPTION
**Pull request by behdad**
Fixes https://github.com/fonttools/fonttools/issues/2769

I don't know how no one noticed this before or how it worked before.

### CODE REVIEW

**Comment by anthrotype** [comment]
good catch

> I don't know how no one noticed this before or how it worked before.

don't know either, but we should add a test to avoid regressions in the future

**Comment by behdad** [comment]
Perhaps some other module in that test has already imported varLib.varStore...

**Comment by anthrotype** [comment]
> Perhaps some other module in that test has already imported varLib.varStore...

possibly..

**Comment by behdad** [comment]
Any test font (like what we have in tree) should do. It just has to be a new test file I think.

**Comment by anthrotype** [comment]
indeed, if you try to run _only_ that tests, it currently faisl on main:

```
$ pytest Tests/subset/subset_test.py::SubsetTest::test_HVAR_VVAR_retain_gids\
========================== test session starts ==========================
platform darwin -- Python 3.10.2, pytest-7.0.1, pluggy-1.0.0
Using --randomly-seed=1587072497
rootdir: /Users/clupo/Github/fonttools, configfile: setup.cfg
plugins: mock-3.7.0, randomly-3.11.0
collected 1 item

Tests/subset/subset_test.py F                                     [100%]

=============================== FAILURES ================================
_________________ SubsetTest.test_HVAR_VVAR_retain_gids _________________

self = <subset_test.SubsetTest object at 0x122ab9240>

    def test_HVAR_VVAR_retain_gids(self):
        fontpath = self.compile_font(self.getpath("TestHVVAR.ttx"), ".ttf")
        subsetpath = self.temp_path(".ttf")
>       subset.main([fontpath, "--text=BD", "--retain-gids", "--output-file=%s" % subsetpath])

Tests/subset/subset_test.py:695:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
Lib/fontTools/misc/loggingTools.py:372: in wrapper
    return func(*args, **kwds)
Lib/fontTools/subset/__init__.py:3210: in main
    subsetter.subset(font)
Lib/fontTools/subset/__init__.py:3018: in subset
    self._subset_glyphs(font)
Lib/fontTools/subset/__init__.py:2963: in _subset_glyphs
    retain = table.subset_glyphs(self)
Lib/fontTools/subset/__init__.py:2007: in subset_glyphs
    varidx_map = table.VarStore.subset_varidxes(used, retainFirstMap=retainAdvMap, advIdxes=advIdxes_)
Lib/fontTools/ttLib/tables/otBase.py:815: in __getattr__
    return getattr(self, attr)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <fontTools.ttLib.tables.otTables.VarStore object at 0x122aba890>
attr = 'subset_varidxes'

    def __getattr__(self, attr):
        reader = self.__dict__.get("reader")
        if reader:
                del self.reader
                font = self.font
                del self.font
                self.decompile(reader, font)
                return getattr(self, attr)

>       raise AttributeError(attr)
E    AttributeError: subset_varidxes

Lib/fontTools/ttLib/tables/otBase.py:817: AttributeError
======================== short test summary info ========================
FAILED Tests/subset/subset_test.py::SubsetTest::test_HVAR_VVAR_retain_gids
=========================== 1 failed in 0.30s ===========================
(
```

**Comment by anthrotype** [comment]
it passes with your fix. Merging!

**Comment by anthrotype** [comment]
it might not be super ideal that we have all these methods magically added as a side effect of importing some module (there's pros and cons to that), but we can revise this later. For now I'll just make a bugfix release with this patch.

**Comment by qxliu76** [comment]
It's working in 4.36.0 release. Thanks for the quick fix!

**Comment by anthrotype** [comment]
is it? I actually haven't made a new release yet :)

**Comment by anthrotype** [comment]
give me a couple minutes to draft the changelog and will push a new tag

**Comment by qxliu76** [comment]
I mean some change between 4.36.0 and 4.37.0 might break it. It's working in 4.36.0 release.

**Comment by anthrotype** [comment]
AH! the reason it works with 4.36.0 but not with 4.37.0 is that in the meantime this commit was added d4d8c4ac5 which removed a seemingly unused import `from fontTools.varLib.varStore import VarStoreInstancer` from the `fontTools/subset/cff.py` module...

**Comment by anthrotype** [comment]
@qxliu76 https://github.com/fonttools/fonttools/releases/tag/4.37.1

**Comment by qxliu76** [comment]
> @qxliu76 https://github.com/fonttools/fonttools/releases/tag/4.37.1

Thank you!

**Pull request merged**
