### PR TITLE
[feaLib.ast] Restore compatibility with 4.9.0

### PR DESCRIPTION
**Pull request by dscorbett**
Version 4.10.0 broke `feaLib.ast.ChainContextPosStatement` and `ChainContextSubstStatement`. Previously each of these classes had a `lookups` field that was a list of lookups. #1905 changed it to a list of lists of lookups. For compatibility, it should treat a lookup within the outer list as if it were a list of a single entry.

In 4.9.0, and once again with my fix, this script:
```python3
#!/usr/bin/env python3

from fontTools.feaLib.ast import (
    ChainContextSubstStatement,
    GlyphName,
    LookupBlock,
)

print(ChainContextSubstStatement(
    [],
    [GlyphName('x')],
    [],
    [LookupBlock('dummy')],
))
```
printed this:
```
sub x' lookup dummy;
```
In 4.10.0, it prints this:
```
Traceback (most recent call last):
  File "./bug.py", line 13, in <module>
    [LookupBlock('dummy')],
  File "/usr/local/lib/python3.7/site-packages/fontTools/feaLib/ast.py", line 128, in __str__
    return self.asFea()
  File "/usr/local/lib/python3.7/site-packages/fontTools/feaLib/ast.py", line 690, in asFea
    for lu in self.lookups[i]:
TypeError: 'LookupBlock' object is not iterable
```

Please merge this, or something similar, and release 4.10.1.

### CODE REVIEW

**Comment by dscorbett** [comment]
@simoncozens, what do you think of the rewording of the docstring?

**Comment by simoncozens** [comment]
Feels a bit funny to say that it's a list of lists, but then in a later sentence say it doesn't have to be. I suggest rewriting the paragraph to say it's a list made up elements which are either lists or bare lookups.

**Comment by dscorbett** [comment]
I’ve updated the documentation.

The fix I implemented is to mutate the lookup list passed to the `ChainContextPosStatement`/`ChainContextSubstStatement` constructor. An alternative is to create a temporary one-element list whenever necessary, without storing it in a field, like this:
https://github.com/fonttools/fonttools/blob/db26cf804e3380b5e9caed3a33d640b8e8a54835/Lib/fontTools/feaLib/builder.py#L229-L231
Any preference?

**Comment by anthrotype** [comment]
@dscorbett it shouldn't matter in most circimstaces, but to avoid surprises, it's probably safer to avoid mutating the input list.

**Comment by dscorbett** [comment]
I agree. I’ll make that change soon.

**Comment by anthrotype** [comment]
actually, I prefer if the ChainContext{Subst,Pos}Statement's constructor normalizes a bare list of lookups to list of lists of lookups. Only the ast classes should change to accommodate the old and new behavior, not also the builder.

**Comment by anthrotype** [comment]
what I mean is inside `__init__` you make sure self.lookups is always a list of lists of lookups, then later other code (in asFea() or builder) can assume that will be the case.

**Comment by dscorbett** [comment]
Okay, so basically what I had at first, except mutating a copy of the input list instead of the input list?

**Comment by anthrotype** [comment]
yes that's what I meant, thank you!

**Pull request merged**
