### PR TITLE
[ttFont] Add reorderGlyphs

### PR DESCRIPTION
**Pull request by behdad**
Fixes https://github.com/fonttools/fonttools/issues/2060

Manually tested; need to add real tests.

### CODE REVIEW

**Review by khaledhosny — APPROVED** [review]

**Review by rsheeter — APPROVED** [review]

**Comment by behdad** [comment]
Do we have any volunteers to write a test?

**Comment by khaledhosny** [comment]
I can work on a test.

**Comment by behdad** [comment]
Thank you.

**Comment by behdad** [comment]
Beautiful. Thank you.

**Pull request merged**
