### PR TITLE
Fix visual artefacts with partial L2 instancing

### LINKED ISSUE #3634: Large visual artefacts when L2 instancing a partial VF with IUP optimisation
To produce inferred deltas that will be correct given [OpenType's `gvar` semantics](https://learn.microsoft.com/en-us/typography/opentype/spec/gvar#inferred-deltas-for-un-referenced-point-numbers), fontTool's IUP optimisation module [checks the equality of some points](https://github.com/fonttools/fonttools/blob/11343ed64c10d3905f4fb4c8d2810c9612ee8acd/Lib/fontTools/varLib/iup.py#L57). However, this happens **before** the points are rounded, whereas the point comparison that happens at runtime will occur **after** the points are rounded (as is necessary to serialise `glyf`), which leads to diverging semantics and so diverging and incorrect implied deltas.

https://github.com/fonttools/fonttools/blob/11343ed64c10d3905f4fb4c8d2810c9612ee8acd/Lib/fontTools/varLib/iup.py#L57-L63

This leads to significant visual artefacts, e.g. where large deltas that should be inferred based on previous values are instead interpreted as 0 at runtime.

I suspect this has gone undetected as the subsetter normally works with rounded points; in the rarer case that partial VF instancing is occurring with a different default position, however, `varLib.instancer` will calculate and [apply the relevant deltas to the font's original coordinates](https://github.com/fonttools/fonttools/blob/11343ed64c10d3905f4fb4c8d2810c9612ee8acd/Lib/fontTools/varLib/instancer/__init__.py#L881) to effect the new default position, which leads to unrounded points in memory.

https://github.com/fonttools/fonttools/blob/11343ed64c10d3905f4fb4c8d2810c9612ee8acd/Lib/fontTools/varLib/instancer/__init__.py#L875-L881

---

I have a patch that rounds earlier and fixes the problem in a test font, and will start a PR this morning :)

### PR DESCRIPTION
**Pull request by Hoolean**
Fixes #3634

The issue above emerges when assumptions are made about point equality based on unrounded points, whereas the comparisons that happen at runtime will be based on rounded points. In particular, unrounded points are present when `varLib.instancer` calculates and applies deltas to the font's original coordinates to effect a new default position, and so this PR rounds immediately after this happens to ensure that the coordinates match those in the final `glyf` table.

---

### To undraft

- [x] Check tests
- [x] Add regression test with minimal reproducer

#### Further

- [x] See if deltas need rounding too?
- [x] See if CFF2 code path is affected?
- [x] See if `iup.py` should instead work with `int`s for point or delta comparison (potentially still using the original `double`s to evaluate tolerance?)
- [x] Confirm comment on unrounded coordinates below

### CODE REVIEW

**Comment by Hoolean** [comment]
Some tests are failing because they expect unrounded coordinates; these were added based on 0010a3cd9aa25f84a3a6250dafb119743d32aa40, and so we'll have to be careful that we preserve the semantics this was intended to preserve.

My loose understanding is that rounding after the deltas are already applied to `glyf` is late enough and will match the implicit rounding that will happen when calculating metrics, but we should confirm.

**Comment by behdad** [comment]
The analysis is spot-on. Lemme digest the proposed solution for any side-effects.

**Comment by behdad** [comment]
> #### Further
> * [ ]  See if deltas need rounding too?

See https://github.com/fonttools/fonttools/pull/2214/commits/68004b8fec94729b7cfe9755eb956fa39feff5de.  Not sure what should happen during instancing.

> * [ ]  See if CFF2 code path is affected?

Good question.

> * [ ]  See if `iup.py` should instead work with `int`s for point or delta comparison (potentially still using the original `double`s to evaluate tolerance?)

Maybe we can add a round parameter there that defaults to noRound to preserve existing behavior. But I think what you have is fine, and letting the tolerance take care of it...

> * [ ]  Confirm comment on unrounded coordinates below

**Comment by Hoolean** [comment]
I've stepped through again with a debugger and it looks like the deltas are always rounded before they reach IUP optimisation, so we should not be at risk of the same rounding issue that affected coordinates:

https://github.com/fonttools/fonttools/blob/11343ed64c10d3905f4fb4c8d2810c9612ee8acd/Lib/fontTools/varLib/instancer/__init__.py#L866-L878

https://github.com/fonttools/fonttools/blob/11343ed64c10d3905f4fb4c8d2810c9612ee8acd/Lib/fontTools/varLib/instancer/__init__.py#L559-L561

I've ticked that point off in the PR description 🚀

**Comment by behdad** [comment]
> * [ ]  See if CFF2 code path is affected?

CFF2 doesn't have IUP.  So we should be good I think.

**Comment by Hoolean** [comment]
> - [ ] Confirm comment on unrounded coordinates below
> > Some tests are failing because they expect unrounded coordinates; these were added based on [0010a3c](https://github.com/fonttools/fonttools/commit/0010a3cd9aa25f84a3a6250dafb119743d32aa40), and so we'll have to be careful that we preserve the semantics this was intended to preserve.
> >
> > My loose understanding is that rounding after the deltas are already applied to `glyf` is late enough and will match the implicit rounding that will happen when calculating metrics, but we should confirm.

I revisited Cosimo's commit (0010a3cd9aa25f84a3a6250dafb119743d32aa40) and `glyf`'s metrics implementation, and now believe that it's important that we pass `glyf` unrounded coordinates. `glyf` uses the rounded diff of unrounded coordinates, which can be different to the rounded diff of rounded coordinates.

https://github.com/fonttools/fonttools/blob/9563608df9eeadef487d4143bed34f796ad15421/Lib/fontTools/ttLib/tables/_g_l_y_f.py#L480-L493

With this in mind, I've made the patch round directly prior to IUP optimisation instead of directly after applying deltas to the default coordinates.

This ensures that all existing uses of the coordinates will continue to use unrounded coordinates, unchanged, with only IUP opimisation receiving the rounded coordinates that it requires. This preserves the side-bearings backwards compatibility with `varLib.mutator` that Cosimo's original commit intends, and so also allowed me to revert the changes we had to make to expected values in existing tests.

(this change was made with a rebase to avoid git history having two directly contradicting rationales)

**Comment by Hoolean** [comment]
> > * [ ]   See if `iup.py` should instead work with `int`s for point or delta comparison (potentially still using the original `double`s to evaluate tolerance?)
> 
> Maybe we can add a round parameter there that defaults to noRound to preserve existing behavior. But I think what you have is fine, and letting the tolerance take care of it...

Having thought on this some more, I think that any invocation of `iup.py` with coordinates or deltas with fractional parts is at risk of being unsound, as the fractional parts can never be represented in the final font in any context, and so coordinate or delta equality would always be at risk of being incorrect after rounding.

L2 instancing is the only place where we have found a real-world issue with this so far though, and so I will tick this off here to avoid holding our fix back with something that might just be hypothetical. I'll make a spin-off issue to cover this though, in case we are calling the `iup.py` with fractional parts anywhere else and it hasn't surfaced an issue yet :)

**Comment by Hoolean** [comment]
Ready for review now!

@behdad Thanks again for the guidance Behdad :)

**Comment by behdad** [comment]
> Ready for review now!
> 
> @behdad Thanks again for the guidance Behdad :)

Thank *you*! Given that @anthrotype is on leave, let's merge this. LGTM.

**Pull request merged**
