### PR TITLE
Change gasp merge logic to 'first'

### PR DESCRIPTION
**Pull request by zjusbo**
Reference #859 
Still open to other ideas.

### CODE REVIEW

**Comment by zjusbo** [comment]
The test fails due to https://github.com/fonttools/fonttools/pull/857

**Comment by behdad** [comment]
I'd say `onlyExisting(equal)` is better.

**Comment by zjusbo** [comment]
I guess you are suggesting:

ttLib.getTableClass('gasp').mergeMap = {
	'tableTag': onlyExisting(equal),
	'version': onlyExisting(max), # max(NotImplemented, 1) returns NotImplemented
	'gaspRange': onlyExisting(first), # FIXME? Appears irreconcilable
}

The difference between these two options happens in this case

fontA['gasp'] = NotImplemented
fontB['gasp'] = a gasp table that is designed for glyphs in fontB

**pyftmerge fontA, fontB**

Your option returns the gasp in fontB while current option drops gasp and returns nothing. 

I think the root problem is: does a gasp table designed for fontB probably hurt the legibility of fontA?

If so, probably dropping the gasp in fontB is a better choice? Actually, default rules to decide how to render the glyphs on grayscale devices are used if the gasp table is absent. Using gasp in fontB implicitly drops the default rules in fontA.

**Comment by behdad** [comment]
Actually, since we retain hinting from first don't only, this also has to be first.  Lgtm

**Pull request merged**
