### PR TITLE
Varlib tests

### PR DESCRIPTION
**Pull request by miguelsousa**
Some things worth mentioning:
* the test only covers variable fonts in TrueType format. Haven't tried with OTFs yet, but it's unlikely to work because #805;
* the test doesn't exercise the merging of layout tables; that task is done by `varLib.interpolate_layout.interpolate_layout()`. I plan to add tests for it;
* I noticed some minor discrepancies in the XML output of the tables `GDEF` and `HVAR`, between getting it thru `ttx` and getting it via `font.saveXML()`;
* it may be worth testing the `model` returned by `build()` as well.

### CODE REVIEW

**Comment by anthrotype** [comment]
Thank you Miguel, this is looking good! I only have a few question/observations.

- are the UFO source files used anywhere in the tests? Or you kept them there as a source for the master_ttf_interpolatable TTX test files?

- we usually name the test modules after the modules they test; in the case of `__init__.py` kind of modules, we name it after the package (e.g. `subset_test.py`). So for consistency I'd rename `Tests/varLib/build_test.py` to `Tests/varLib/varLib_test.py`;

> I noticed some minor discrepancies in the XML output of the tables GDEF and HVAR, between getting it thru ttx and getting it via font.saveXML();

Can you tell me a bit more on this differences?

**Comment by anthrotype** [comment]
nice use of Source Serif Pro, btw! :)

**Comment by miguelsousa** [comment]
> are the UFO source files used anywhere in the tests?

No. But I think it's important to keep them around so that we can recreate, modify or increment the input test data easily.

I'll rename the test file.

Regarding the XML differences, I was trying to put together a test snippet but it's not working. So instead, [uncomment this line](https://github.com/fonttools/fonttools/pull/866/files#diff-a9781fb33d9e488d5c55b6960d71f2c2R100), run `ttx -t GDEF -t HVAR -t fvar -t gvar BuildTest.ttf` and compare the two TTX files.

**Comment by twardoch** [comment]
@miguelsousa Am I right to assume that the [test font](https://github.com/miguelsousa/fonttools/tree/varlib-tests/Tests/varLib/data) is licensed under the [fontTools license](https://github.com/fonttools/fonttools/blob/master/LICENSE) ?

**Comment by miguelsousa** [comment]
@twardoch yes. Thanks for asking.

**Comment by anthrotype** [comment]
I used `ttx` to dump the generated BuiltTest.ttf and compared it with the `BuildTest.ttx` that we produce with `font.saveXML()`, I see three sets of differences:

1) `VariationStore.VarData.NumShorts` is not being set by the `varLib.builder`; so when doing `saveXML` without first compiling, it is written as "None"; after rountripping with ttx, it becomes `0`.

2) `VariationStore.VarRegionList.RegionAxisCount` is also not being set by `varLib.builder`; it gets populated only on compile, hence it shows up after roundtripping;

3) `StartCoord`, `PeakCoord` and `EndCoord` are read in by otData as `F2Dot14` so they appear as `float` (e.g. "0.0") after roundtripping; but `varLib.builder` sometimes sets them as integers, so the saveXML output differ from the ttx dump.

I have a patch that fixes these, will push after merging this PR.

Here is the full diff: 

```diff
$ diff -u "Tests/varLib/data/BuildTest.ttx" "Tests/varLib/data/BuildTest#1.ttx"
--- Tests/varLib/data/BuildTest.ttx	2017-03-01 15:37:39.000000000 +0000
+++ Tests/varLib/data/BuildTest#1.ttx	2017-03-01 15:38:43.000000000 +0000
@@ -6,15 +6,16 @@
     <VarStore Format="1">
       <Format value="1"/>
       <VarRegionList>
+        <!-- RegionAxisCount=2 -->
         <!-- RegionCount=5 -->
         <Region index="0">
           <VarRegionAxis index="0">
-            <StartCoord value="0"/>
-            <PeakCoord value="0"/>
-            <EndCoord value="0"/>
+            <StartCoord value="0.0"/>
+            <PeakCoord value="0.0"/>
+            <EndCoord value="0.0"/>
           </VarRegionAxis>
           <VarRegionAxis index="1">
-            <StartCoord value="0"/>
+            <StartCoord value="0.0"/>
             <PeakCoord value="1.0"/>
             <EndCoord value="1.0"/>
           </VarRegionAxis>
@@ -23,46 +24,46 @@
           <VarRegionAxis index="0">
             <StartCoord value="-1.0"/>
             <PeakCoord value="-1.0"/>
-            <EndCoord value="0"/>
+            <EndCoord value="0.0"/>
           </VarRegionAxis>
           <VarRegionAxis index="1">
-            <StartCoord value="0"/>
-            <PeakCoord value="0"/>
-            <EndCoord value="0"/>
+            <StartCoord value="0.0"/>
+            <PeakCoord value="0.0"/>
+            <EndCoord value="0.0"/>
           </VarRegionAxis>
         </Region>
         <Region index="2">
           <VarRegionAxis index="0">
-            <StartCoord value="0"/>
+            <StartCoord value="0.0"/>
             <PeakCoord value="1.0"/>
             <EndCoord value="1.0"/>
           </VarRegionAxis>
           <VarRegionAxis index="1">
-            <StartCoord value="0"/>
-            <PeakCoord value="0"/>
-            <EndCoord value="0"/>
+            <StartCoord value="0.0"/>
+            <PeakCoord value="0.0"/>
+            <EndCoord value="0.0"/>
           </VarRegionAxis>
         </Region>
         <Region index="3">
           <VarRegionAxis index="0">
             <StartCoord value="-1.0"/>
             <PeakCoord value="-1.0"/>
-            <EndCoord value="0"/>
+            <EndCoord value="0.0"/>
           </VarRegionAxis>
           <VarRegionAxis index="1">
-            <StartCoord value="0"/>
+            <StartCoord value="0.0"/>
             <PeakCoord value="1.0"/>
             <EndCoord value="1.0"/>
           </VarRegionAxis>
         </Region>
         <Region index="4">
           <VarRegionAxis index="0">
-            <StartCoord value="0"/>
+            <StartCoord value="0.0"/>
             <PeakCoord value="1.0"/>
             <EndCoord value="1.0"/>
           </VarRegionAxis>
           <VarRegionAxis index="1">
-            <StartCoord value="0"/>
+            <StartCoord value="0.0"/>
             <PeakCoord value="1.0"/>
             <EndCoord value="1.0"/>
           </VarRegionAxis>
@@ -71,7 +72,7 @@
       <!-- VarDataCount=1 -->
       <VarData index="0">
         <!-- ItemCount=0 -->
-        <NumShorts value="None"/>
+        <NumShorts value="0"/>
         <!-- VarRegionCount=5 -->
         <VarRegionIndex index="0" value="0"/>
         <VarRegionIndex index="1" value="1"/>
@@ -87,15 +88,16 @@
     <VarStore Format="1">
       <Format value="1"/>
       <VarRegionList>
+        <!-- RegionAxisCount=2 -->
         <!-- RegionCount=5 -->
         <Region index="0">
           <VarRegionAxis index="0">
-            <StartCoord value="0"/>
-            <PeakCoord value="0"/>
-            <EndCoord value="0"/>
+            <StartCoord value="0.0"/>
+            <PeakCoord value="0.0"/>
+            <EndCoord value="0.0"/>
           </VarRegionAxis>
           <VarRegionAxis index="1">
-            <StartCoord value="0"/>
+            <StartCoord value="0.0"/>
             <PeakCoord value="1.0"/>
             <EndCoord value="1.0"/>
           </VarRegionAxis>
@@ -104,46 +106,46 @@
           <VarRegionAxis index="0">
             <StartCoord value="-1.0"/>
             <PeakCoord value="-1.0"/>
-            <EndCoord value="0"/>
+            <EndCoord value="0.0"/>
           </VarRegionAxis>
           <VarRegionAxis index="1">
-            <StartCoord value="0"/>
-            <PeakCoord value="0"/>
-            <EndCoord value="0"/>
+            <StartCoord value="0.0"/>
+            <PeakCoord value="0.0"/>
+            <EndCoord value="0.0"/>
           </VarRegionAxis>
         </Region>
         <Region index="2">
           <VarRegionAxis index="0">
-            <StartCoord value="0"/>
+            <StartCoord value="0.0"/>
             <PeakCoord value="1.0"/>
             <EndCoord value="1.0"/>
           </VarRegionAxis>
           <VarRegionAxis index="1">
-            <StartCoord value="0"/>
-            <PeakCoord value="0"/>
-            <EndCoord value="0"/>
+            <StartCoord value="0.0"/>
+            <PeakCoord value="0.0"/>
+            <EndCoord value="0.0"/>
           </VarRegionAxis>
         </Region>
         <Region index="3">
           <VarRegionAxis index="0">
             <StartCoord value="-1.0"/>
             <PeakCoord value="-1.0"/>
-            <EndCoord value="0"/>
+            <EndCoord value="0.0"/>
           </VarRegionAxis>
           <VarRegionAxis index="1">
-            <StartCoord value="0"/>
+            <StartCoord value="0.0"/>
             <PeakCoord value="1.0"/>
             <EndCoord value="1.0"/>
           </VarRegionAxis>
         </Region>
         <Region index="4">
           <VarRegionAxis index="0">
-            <StartCoord value="0"/>
+            <StartCoord value="0.0"/>
             <PeakCoord value="1.0"/>
             <EndCoord value="1.0"/>
           </VarRegionAxis>
           <VarRegionAxis index="1">
-            <StartCoord value="0"/>
+            <StartCoord value="0.0"/>
             <PeakCoord value="1.0"/>
             <EndCoord value="1.0"/>
           </VarRegionAxis>
@@ -152,7 +154,7 @@
       <!-- VarDataCount=1 -->
       <VarData index="0">
         <!-- ItemCount=6 -->
-        <NumShorts value="None"/>
+        <NumShorts value="0"/>
         <!-- VarRegionCount=5 -->
         <VarRegionIndex index="0" value="0"/>
         <VarRegionIndex index="1" value="1"/>
```

**Comment by behdad** [comment]
Thanks Miguel!

**Pull request merged**
