### PR TITLE
[otlLib.builder._addName] raise exception if nameID does not exist

### PR DESCRIPTION
**Pull request by m4rc1e**
`buildStatTable` in otlLib builds a STAT table from a python dictionary. AxisValue names can either be a string or an int. If an int is used, it'll simply find a name table name record with the same nameID as the int. This pr will raise an exception if a user tries to get a name record that doesn't exist.

I uncovered this issue while working on Merriweather. The family's opsz axis has the following yaml:

```YAML
  - name: Weight
    ...
  - name: Optical Size
    tag: opsz
    values:
    - name: 12
      value: 12
    - name: 14
      value: 14
    - name: 16
      value: 16
    - name: 24
      value: 24
    - name: 48
      value: 48
    - name: 64
      value: 64
    - name: 72
      value: 72
    - name: 144
      value: 144
```

if i ttx the table, I get:

```XML
 <AxisValue index="13" Format="1">
        <AxisIndex value="2"/>
        <Flags value="0"/>
        <ValueNameID value="24"/>  <!-- missing from name table -->
        <Value value="24.0"/>
      </AxisValue>
      <AxisValue index="14" Format="1">
        <AxisIndex value="2"/>
        <Flags value="0"/>
        <ValueNameID value="48"/>  <!-- missing from name table -->
        <Value value="48.0"/>
      </AxisValue>
      <AxisValue index="15" Format="1">
        <AxisIndex value="2"/>
        <Flags value="0"/>
        <ValueNameID value="64"/>  <!-- missing from name table -->
        <Value value="64.0"/>
      </AxisValue>
      <AxisValue index="16" Format="1">
        <AxisIndex value="2"/>
        <Flags value="0"/>
        <ValueNameID value="72"/>  <!-- missing from name table -->
        <Value value="72.0"/>
      </AxisValue>
      <AxisValue index="17" Format="1">
        <AxisIndex value="2"/>
        <Flags value="0"/>
        <ValueNameID value="144"/>  <!-- missing from name table -->
        <Value value="144.0"/>
```

What the author actually wanted is for the names to be strings such as "12pt", "144pt" etc.

Happy to fix tests if current approach is accepted.

### CODE REVIEW

**Comment by anthrotype** [comment]
> What the author actually wanted is for the names to be strings such as "12pt", "144pt" etc.

then, should they actually have written them as string literals (e.g. within double quotes) instead of as integers? Or can't yaml distinguish those?

Note that I'm not opposed to have a check for existing nameIDs which could be useful in its own right (even though, one may wish to first build a STAT and then a name table that matches those nameIDs, which this PR would prevent); it's more like this is not a direct fix for your problem, which was that the caller were holding the function wrong, so to speak: i.e. passing in integers (which are assumed to be nameIDs) instead of strings (for which new name records are created).

**Comment by anthrotype** [comment]
(clicked the wrong button sorry)

**Comment by m4rc1e** [comment]
> then, should they actually have written them as string literals (e.g. within double quotes) instead of as integers? Or can't yaml distinguish those?

The designer should've written them in double quotes.

> one may wish to first build a STAT and then a name table that matches those nameIDs, which this PR would prevent

Good point!

I don't mind closing this PR and doing the validation in gftools gen-stat instead.

**Comment by m4rc1e** [comment]
Going to close this and do the check in gftools instead. Thanks Cosimo!

**Pull request closed without merging**
