### PR TITLE
WIP: merge CFF

### PR DESCRIPTION
**Pull request by anthrotype**
continuation of #1289

### CODE REVIEW

**Comment by behdad** [comment]
Is this still valid?

**Comment by anthrotype** [comment]
@BlackFoundry are you going to finish work on this? If you can't right now, it's ok. Just remove from the "Assignees" list, thanks.

**Comment by BlackFoundry** [comment]
More likely later, beginning 2019, right now is quite busy. Could @behdad  help too?

**Comment by BlackFoundry** [comment]
Next step would be to implement CIDFonts merging. Would be nice to have some Adobe CFF expert guidance.

**Comment by readroberts** [comment]
@BlackFoundry Sure. The only real difference is that you have to track the FDArray list, and update the fdSelect index value in each charstring.  I would first merge all the charstrings specified, keeping track of the charstrings added. For each charstring that you added from the second font to the first, you need to check the FontDict referenced by the fdSelect index value.  IF you can find a a pre-existing FontDict in the first font's FDArray that you can use instead, you just need to update all the relevant charstrings to reference that FDArray, else you just add the second fonts's FontDict to the first font's FDArray. ( you can use any pre-existing FontDict with has then same PrivateDict values). When you are all done, the two fonts will be cross-linked - for example, any new FontDicts added to the first font will be pointing to PrivateDicts that are in the second font - but this will all be flattened correctly when you compile. Feel free to e-mail me directly, rroberts@adobe.com

**Comment by anthrotype** [comment]
@BlackFoundry any updates on this?

**Comment by indirectlylit** [comment]
refs #1319 I believe?

**Comment by khaledhosny** [comment]
I’d like to get this merged without CID support since it is both less and less relevant these days and apparently no one is going to work on it anytime soon. @anthrotype anything you want to fix here other than CID support?

**Comment by khaledhosny** [comment]
I have this locally rebased against main, but I had to drop the `.notdef` stuff it conflicts with #1729. Should I force-push to this branch and PR, or open a new one?

**Comment by behdad** [comment]
> open a new one?

Do that.

**Comment by khaledhosny** [comment]
https://github.com/fonttools/fonttools/pull/2447

**Pull request closed without merging**
