### PR TITLE
Cache repeated subtables while building COLR

### PR DESCRIPTION
**Pull request by simoncozens**
When building a complex COLR table, particularly for a font with a large number of glyphs, there can be *many* repeated subtables. Instead of rebuilding each subtable from scratch, a simple cache can be used to speed up the build.

For example, building [Bitcount](https://bitcount.typenetwork.com) without the cache takes 274 seconds on my computer; with the cache,  it takes 94.

### CODE REVIEW

**Comment by simoncozens** [comment]
...but this only works when you're sending a plain JSON-style object to `buildPaint`, not a mix of dictionaries and pre-compiled subtables...

**Comment by anthrotype** [comment]
hm yeah, the API supports a mix of raw dicts and prebuilt subtables and I'd like to keep that way. Also I'm a bit meh on having KBs of JSON for the cache dict keys..

**Comment by anthrotype** [comment]
I'm worried about the potential risk of collisions when using hash instead of the strings themselves as the key. This SO suggests using more cryptographically robust hashlib (also in stdlib).
Also I think pickle is faster than json in general.

**Comment by anthrotype** [comment]
also how about we make this caching optional by adding a parameter to the buildCOLR table that trickles down to the TableBuilder constructor? Maybe for your particular use case this may make things faster, but for the general case I am not sure whether the cost of pickling and caching outweighs the benefits

**Comment by simoncozens** [comment]
Closing in favour of #3221

**Comment by anthrotype** [comment]
> Closing in favour of https://github.com/fonttools/fonttools/pull/3221

my PR was based off yours, the idea was if you liked that suggestion you could merge that first into your PR branch and proceed from there. But since you closed this one I have rebased my PR onto main. Feel free to pick that one up

**Pull request closed without merging**
