### PR TITLE
Visitor inheritance

### LINKED ISSUE #3580: Visitor pattern does not search inheritance chain
Unfortunately, I can't do this:

```python
from fontTools.feaLib import ast

@GlyphFilterVisitor.register(ast.Statement)
def visit(visitor, statement, *args, **kwargs):
    print("This never fires")
```

This is because the visitor looks for a registered `visitor` function for the exact class name of the object, and does not search the class hierarchy to find any superclass visitors.

### PR DESCRIPTION
**Pull request by simoncozens**
With this PR, a visitor object will look for registered visitors on an objects superclasses as well as on the object itself, fixes #3580.

### CODE REVIEW

**Comment by behdad** [comment]
Perfect. Thanks.

**Comment by behdad** [comment]
Are we happy with the order of things? Right now we'll pick a more generic visit from the visitor subclass rather than a more specific visit from a parent visitor. I don't think it's a big deal, but the other way around might make more sense?

**Comment by simoncozens** [comment]
I can argue it both ways. :-) But I think the current way is best.

In `parent.py`:

```
@Supervisitor.register(ast.AlternateSubstStatement)
def visit(visitor, statement, *args, **kwargs):
    print("Do stuff")
```

In `child.py`:

```
class Subvisitor(Supervisitor):
    pass

@Supervisitor.register(ast.Statement)
def visit(visitor, statement, *args, **kwargs):
    print("*This* is what I want you to do on a statement, nothing else!")
```

**Comment by behdad** [comment]
Sounds good to me.

**Pull request merged**
