### PR TITLE
[glyf] compile empty table as 1 null byte to make OTS and Windows happy

### LINKED ISSUE #899: add 1 zero byte when compiling empty glyf tables...
...to make Windows happy.

The OTS does that too now.

See discussion
https://github.com/khaledhosny/ots/issues/52#issuecomment-289369267

### PR DESCRIPTION
**Pull request by anthrotype**
OTS rejects fonts with empty tables, and Windows considers the font file invalid if a table is empty.
See discussion https://github.com/khaledhosny/ots/issues/52
When a glyf table is empty (e.g. all glyphs are zero contours) we compile it as a single zero byte `b'\x00'`, which will make it pass OTS.

Fixes https://github.com/fonttools/fonttools/issues/899

### CODE REVIEW

**Comment by behdad** [comment]
I'm against this.

**Comment by behdad** [comment]
Ah doing it just for `glyf` table.  Yeah am fine with that.

**Review by justvanrossum — APPROVED** [review]

**Comment by anthrotype** [comment]
Yes only for glyf. OTS does the same.

**Pull request merged**
