### PR TITLE
Switch to GitHub Actions

### PR DESCRIPTION
**Pull request by madig**
Let's see if this works! Travis is going to wind down their open source program.

### CODE REVIEW

**Comment by madig** [comment]
Ide thought: before I some day fix the Windows issue about relative paths, should pypy3 and cython be tested on more platforms? I already find it wasteful to test 3.6-3.9 on all platforms...

**Comment by anthrotype** [comment]
cython and pypy just on linux.
macos and windows only on latest (stable) python: i.e. py3.8, whatever homebrew is the default.
for linux only, all the python3s

**Comment by moyogo** [comment]
Isn’t py3.9 the default on homebrew now?

**Comment by madig** [comment]
Not sure Homebrew is used on macOS but 3.9 is available. Once we sort out the Windows relpath issues we'll see if everything works :)

**Comment by benkiel** [comment]
Thanks for this, watching closely to learn and then change all the RoboTools repositories...

**Comment by madig** [comment]
@anthrotype so, I think this can go in after you set up the secret env vars.

**Comment by anthrotype** [comment]
> this can go in after you set up the secret env vars.

added PYPI_USERNAME and PYPI_PASSWPRD as repo secrets in the settings. I hope that works.

**Comment by madig** [comment]
Only one way to find out.

**Pull request merged**
