### PR TITLE
[cubic-glyf] Fix drawPoints() contour ending with cubic offCurve

### PR DESCRIPTION
**Pull request by behdad**
Fixes https://github.com/fonttools/fonttools/issues/3189

### CODE REVIEW

**Comment by behdad** [comment]
> How should an all-offcurve cubic contour be represented in pointPen? It looks the same as a quadratic one, no?

Oh, the lone cubic on-curve with None coordinates I think. Fixing.

**Review by justvanrossum — APPROVED** [review]
LGTM!

**Comment by justvanrossum** [comment]
> How should an all-offcurve cubic contour be represented in pointPen? It looks the same as a quadratic one, no?

That is a design flaw in the point pen protocol, that is reflected in UFO outlines, too.

**Comment by behdad** [comment]
Filed https://github.com/fonttools/fonttools/issues/3191.

**Pull request merged**
