### PR TITLE
CFF convertors more fixes

### PR DESCRIPTION
**Pull request by behdad**
So far in `CFFToCFF2`. Hoping to find what's so broken with `CFF2ToCFF` as well.

### CODE REVIEW

**Comment by behdad** [comment]
Humm. `CFF2ToCFF` still fails with `recalcBBoxes=False`. Is rather hard to fix, since the CFF table has cid names and the rest of the font have the original names...

**Comment by behdad** [comment]
> Humm. `CFF2ToCFF` still fails with `recalcBBoxes=False`. Is rather hard to fix, since the CFF table has cid names and the rest of the font have the original names...

Since we are converting the CFF2 to a CID-keyed CFF, the glyphnames are going to be dropped. We might not be able to just change create the `CFF ` table and compile the font :(.  I'll see if I can hack `cffLib` to work though.

**Comment by behdad** [comment]
We really need a CFF lawyer. Maybe I can get help from Ken Lunde.

**Comment by punchcutter** [comment]
Since a CFF2 font from CID-keyed sources doesn't have any recollection of the ROS there's no way to know the CID mapping unless that can be passed along as another parameter and understood.

**Comment by behdad** [comment]
> Since a CFF2 font from CID-keyed sources doesn't have any recollection of the ROS there's no way to know the CID mapping unless that can be passed along as another parameter and understood.

Humm. I'm encoding a charset in the CFF file. What I don't understand is how all software seems to accept CID-keyed fonts (ie. FDSelect etc) without ROS. Or am I wrong and that's a valid CFF?

**Comment by punchcutter** [comment]
I'm not sure how you can have CID-keyed without a ROS. For any ROS other than Adobe-Identity-0 it's THE thing that tells you what's what.

**Comment by behdad** [comment]
> I'm not sure how you can have CID-keyed without a ROS. For any ROS other than Adobe-Identity-0 it's THE thing that tells you what's what.

**Comment by punchcutter** [comment]
There's also no guarantee of a post 2.0 table with glyph names. So it really feels like we need some extra data to properly cover all possible CID situations.

**Comment by khaledhosny** [comment]
AFDKO’s tx can convert CFF2 to CFF, may be try it to see what it is doing in these situations?

**Comment by punchcutter** [comment]
tx doesn't do anything. I think it has a bug and sets the ROS to Adobe-Identity-1 which isn't a thing. I use tx for this, but only for the outline data and then I need to build the new OTF with makeotf. tx can't pull a finished OTF instance like fonttools can.

**Comment by behdad** [comment]
> sets the ROS to Adobe-Identity-1 which isn't a thing

What do you mean it isn't a thing?

**Comment by behdad** [comment]
Oh, I didn't realize there's Adobe-Identity-0 and Adobe-Identity-1. That said, HB code doesn't do anything with the ROS. So it's basically assuming an identity map?

**Comment by behdad** [comment]
> Oh, I didn't realize there's Adobe-Identity-0 and Adobe-Identity-1. That said, HB code doesn't do anything with the ROS. So it's basically assuming an identity map?

Or said another way, are these relevant in OT fonts? Or cmap skips the ROS / charset mapping?

**Comment by behdad** [comment]
I'm not sure what to do here, but I suggest merging. The command-line `CFF2ToCFF` seems to work well; not so much the function, since TTFont's recalcBBoxes=True fails. I'll keep thinking about a solution.

**Comment by behdad** [comment]
Not sure what to do about this. Land? The code is still a mystery to me, but I don't see what letting this rot will buy us.

**Comment by anthrotype** [comment]
maybe merge but file an issue summarizing the remaining problems?

**Review by khaledhosny — APPROVED** [review]
I second what @anthrotype said above.

**Comment by behdad** [comment]
Thanks. The issue remains to be https://github.com/fonttools/fonttools/issues/3521 I'll comment there.

**Pull request merged**
