### PR TITLE
Mti lib tests

### PR DESCRIPTION
**Pull request by behdad**

### CODE REVIEW

**Comment by behdad** [comment]
Part of https://github.com/fonttools/fonttools/issues/585
Fixes https://github.com/fonttools/fonttools/issues/432

**Comment by behdad** [comment]
Ok, I don't know how to install the testdata such that the bots pass.  I don't see how that is done for feaLib/testdata.

**Comment by anthrotype** [comment]
So, the MANIFEST.in is incomplete and also contains a typo:

```diff
diff --git a/MANIFEST.in b/MANIFEST.in
index aeeb6d8..5013cf6 100644
--- a/MANIFEST.in
+++ b/MANIFEST.in
@@ -12,6 +12,8 @@ include tox.ini
 include run-tests.sh
 
 recursive-include Lib/fontTools testdata/*.ttx testdata/*.otx testdata/*.fea
-recursive-invlude Lib/fontTools testdata/*.txt testdata/*.ttx.*
+recursive-include Lib/fontTools testdata/*.txt testdata/*.ttx.*
+recursive-include Lib/fontTools testdata/mti/*.txt testdata/mti/*.ttx.*
+recursive-include Lib/fontTools testdata/mti/*.ttx testdata/mti/README
 recursive-include Lib/fontTools testdata/*.lwfn testdata/*.pfa testdata/*.pfb
 recursive-include Lib/fontTools testdata/*.xml testdata/*.designspace testdata/*.bin
```

But the real problem is elsewhere, and has to do with the different ways hashing works on python 2 and 3, which makes the expected text result differ, sometimes randomly, from the generated results...

The reason why when you run the test module by itself, e.g. `python Lib/fontTools/mtiLib/mti_test.py`, works (at least on python2), whereas running the same test module from within a tox environment fails, is because tox by default sets a special environment variable called `PYTHONHASHSEED` that mimics Python 3's hash randomization, and ensures test failures are reproducible:

http://tox.readthedocs.io/en/latest/example/basic.html#special-handling-of-pythonhashseed
https://docs.python.org/3/using/cmdline.html#envvar-PYTHONHASHSEED

If we disable this behaviour (e.g. `tox --hashseed=noset`), the tests will pass on python2.7 (I suspect the test data was generated with python2.7); however, the same tests will still fail on Python 3, because there the hash seed is random by default -- unless a specific PYTHONHASHSEED is used.

One solution could be to generate the test data with a specific `PYTHONHASHSEED` and pass that value to tox, but I'm not sure if that will work reliably across 2 and 3 (remember we had issues in cu2qu when we tried to reproduce `random.random` results)

A better solution would be to make sure there is nothing left to randomness in the way our data structures are compiled to binary or serialized to xml.

BTW, this other issue could be related to this one, or be part of the same problem:
https://github.com/fonttools/fonttools/issues/766

**Comment by behdad** [comment]
Ok, thanks.  I have not had arrived at the hashing changes yet.  I'll try to fix those properly.

**Comment by anthrotype** [comment]
More info on python 3 hash randomisation:
https://docs.python.org/3/reference/datamodel.html#object.__hash__

**Comment by behdad** [comment]
Thanks.  I'm working on removing the uncertainty.

**Pull request merged**
