### PR TITLE
[ttLib] add rsb attribute to _TTGlyph

### PR DESCRIPTION
**Pull request by m4rc1e**
As discussed in #1074. 

More than happy to add a test if needed.

### CODE REVIEW

**Comment by anthrotype** [comment]
well, it's good that we have some tests already
See https://travis-ci.org/fonttools/fonttools/jobs/288179180#L2939

sometime a glyf Glyph does not have xMax (empty glyphs). 
replace `self._glyph.xMax` with `self.glyph._xMax if hasattr(self._glyph, "xMax") else 0` or similar.

**Comment by m4rc1e** [comment]
@anthrotype thanks, I've forced pushed the fix

**Comment by anthrotype** [comment]
Hm, I wonder... When the xMax is 0 because the glyph has no contours nor components, its right side bearing is also equal to 0, or is it equal to the advance width?

Also, I think this won't work with CFF charstrings, does it? The latter don't have xMax or other bbox attributes

**Comment by justvanrossum** [comment]
I'm fairly sure this implementation of `rsb` is not correct when `lsb != xMin`.

**Comment by justvanrossum** [comment]
I don't think CFF charstrings have an `.lsb` attr even...

**Comment by m4rc1e** [comment]
@justvanrossum Good point. I'll take a look now.

**Comment by justvanrossum** [comment]
Like @anthrotype, I'm not super convinced of this addition. It's a higher level bit of info, which suggests it should also work with charstrings, which it cannot.

**Comment by m4rc1e** [comment]
@justvanrossum @anthrotype Thank you for both raising your valid concerns. Yeah, side-bearings seem to be a concept of font editors.

Closing.

**Comment by justvanrossum** [comment]
Actually, I was wrong, CFF-based fonts still must have an `hmtx` table, so the glyph objects do have an `lsb` attribute. That said, the _main_ reason that the glyph object carries the `lsb` around is so it can calculate an x offset for drawing a TT glyph to a pen.

**Pull request closed without merging**
