### PR TITLE
[varLib.interpolate_layout] Tests for GPOS LookupType 2 class pairs

### PR DESCRIPTION
**Pull request by miguelsousa**
Merging of class kerning pairs seems to be broken.
```python
Traceback (most recent call last):
  File "interpolate_layout_test.py", line 425, in test_varlib_interpolate_layout_GPOS_only_LookupType_2_class_pairs_same_val_ttf
    instfont = interpolate_layout(ds_path, {'weight': 500}, finder)
  File "fonttools/Lib/fontTools/varLib/interpolate_layout.py", line 85, in interpolate_layout
    merger.mergeTables(font, master_fonts, axes_dict, base_idx, ['GPOS'])
  File "fonttools/Lib/fontTools/varLib/merger.py", line 107, in mergeTables
    self.mergeThings(font[tag], [m[tag] for m in master_ttfs])
  File "fonttools/Lib/fontTools/varLib/merger.py", line 93, in mergeThings
    self.mergeObjects(out, lst)
  File "fonttools/Lib/fontTools/varLib/merger.py", line 70, in mergeObjects
    mergerFunc(self, value, values)
  File "fonttools/Lib/fontTools/varLib/merger.py", line 93, in mergeThings
    self.mergeObjects(out, lst)
  File "fonttools/Lib/fontTools/varLib/merger.py", line 70, in mergeObjects
    mergerFunc(self, value, values)
  File "fonttools/Lib/fontTools/varLib/merger.py", line 93, in mergeThings
    self.mergeObjects(out, lst)
  File "fonttools/Lib/fontTools/varLib/merger.py", line 70, in mergeObjects
    mergerFunc(self, value, values)
  File "fonttools/Lib/fontTools/varLib/merger.py", line 95, in mergeThings
    self.mergeLists(out, lst)
  File "fonttools/Lib/fontTools/varLib/merger.py", line 80, in mergeLists
    self.mergeThings(value, values)
  File "fonttools/Lib/fontTools/varLib/merger.py", line 91, in mergeThings
    mergerFunc(self, out, lst)
  File "fonttools/Lib/fontTools/varLib/merger.py", line 531, in merge
    merger.mergeLists(self.SubTable, subtables)
  File "fonttools/Lib/fontTools/varLib/merger.py", line 80, in mergeLists
    self.mergeThings(value, values)
  File "fonttools/Lib/fontTools/varLib/merger.py", line 91, in mergeThings
    mergerFunc(self, out, lst)
  File "fonttools/Lib/fontTools/varLib/merger.py", line 430, in merge
    _PairPosFormat2_merge(self, lst, merger)
  File "fonttools/Lib/fontTools/varLib/merger.py", line 368, in _PairPosFormat2_merge
    self.ClassDef1, classes = _ClassDef_merge_classify([l.ClassDef1 for l in lst], allGlyphs=glyphSet)
  File "fonttools/Lib/fontTools/varLib/merger.py", line 326, in _ClassDef_merge_classify
    sets[0] = set(allGlyphs)
IndexError: ('list assignment index out of range', 'PairPos', '[1]', 'Lookup', '[0]', 'list', '.Lookup', 'LookupList', '.LookupList', 'GPOS', '.table', 'table_G_P_O_S_')
```

### CODE REVIEW

**Comment by behdad** [comment]
Thanks.  Will look into it today.

**Comment by anthrotype** [comment]
looks like this happens when the varLib.merger attempts to merge empty ClassDef1 in PairPos Format 2.

the `_ClassDef_invert` function returns an empty list if the ClassDef1 is empty, but then in `_ClassDef_merge_classify` fails because it attempts to set the first item (of an empty list) to `set[0] = set(allGlyphs)`:

https://github.com/fonttools/fonttools/commit/9544a538eefb0fe37fde4f41be3e5ef84f8f666a#diff-d53a8e57be84b219475e1de32e2de048R326

**Comment by anthrotype** [comment]
I managed to reduce the difference with the expected TTX result to a single line... but I still don't know how to fix that zero value record:

```diff
--- fonttools/Tests/varLib/data/test_results/InterpolateLayoutGPOS_2_class_diff.ttx
+++ /var/folders/jb/rjz76yw92w7144mwqg119jnm0000gn/T/tmpn3zhjarm/tmp1.ttx
@@ -48,6 +48,7 @@
           <!-- Class2Count=2 -->
           <Class1Record index="0">
             <Class2Record index="0">
+              <Value1 XAdvance="0"/>
             </Class2Record>
             <Class2Record index="1">
               <Value1 XAdvance="-40"/>
```

This is the patch so far:

```diff
diff --git a/Lib/fontTools/varLib/merger.py b/Lib/fontTools/varLib/merger.py
index 06a47bd..501d6de 100644
--- a/Lib/fontTools/varLib/merger.py
+++ b/Lib/fontTools/varLib/merger.py
@@ -322,10 +322,12 @@ def _ClassDef_merge_classify(lst, allGlyphs=None):
                sets = _ClassDef_invert(l)
                if allGlyphs is None:
                        sets = sets[1:]
-               else:
+               elif sets:
                        sets[0] = set(allGlyphs)
                        for s in sets[1:]:
                                sets[0].difference_update(s)
+               else:
+                       sets = [set(allGlyphs)]
                classifier.update(sets)
        classes = classifier.getClasses()
 
@@ -506,15 +508,18 @@ def _Lookup_PairPos_subtables_canonicalize(lst, font):
        head = []
        tail = []
        it = iter(lst)
+       has_Format1 = False
        for subtable in it:
                if subtable.Format == 1:
                        head.append(subtable)
+                       has_Format1 = True
                        continue
                tail.append(subtable)
                break
        tail.extend(it)
-       # TODO Only do this if at least one font has a Format1.
-       tail.insert(0, _Lookup_PairPosFormat1_subtables_merge_overlay(head, font))
+       if has_Format1:
+               # only insert if at least one font has a Format1
+               tail.insert(0, _Lookup_PairPosFormat1_subtables_merge_overlay(head, font))
        return tail
 
 @AligningMerger.merger(ot.Lookup)
```

I'll leave it to Behdad.

**Comment by miguelsousa** [comment]
Thanks Cosimo. It's quite possible that the test result is incomplete. I'll double check.

**Comment by miguelsousa** [comment]
Now it fails on the XML roundtrip check e.g. `<ClassDef1>` vs. `<ClassDef1 Format="2">`.

**Comment by miguelsousa** [comment]
This change makes the tests pass. But is it right?
```diff
diff --git a/Lib/fontTools/varLib/merger.py b/Lib/fontTools/varLib/merger.py
index de3c970..a84af6c 100644
--- a/Lib/fontTools/varLib/merger.py
+++ b/Lib/fontTools/varLib/merger.py
@@ -369,6 +369,10 @@ def _PairPosFormat2_merge(self, lst, merger):
        # Align first classes
        self.ClassDef1, classes = _ClassDef_merge_classify([l.ClassDef1 for l in lst], allGlyphs=glyphSet)
        self.Class1Count = len(classes)
+       if self.Class1Count > 1:
+               self.ClassDef1.Format = 1
+       else:
+               self.ClassDef1.Format = 2
        new_matrices = []
        for l,matrix in zip(lst, matrices):
                nullRow = None
@@ -396,6 +400,10 @@ def _PairPosFormat2_merge(self, lst, merger):
        # Align second classes
        self.ClassDef2, classes = _ClassDef_merge_classify([l.ClassDef2 for l in lst])
        self.Class2Count = len(classes)
+       if self.Class2Count > 1:
+               self.ClassDef2.Format = 1
+       else:
+               self.ClassDef2.Format = 2
        new_matrices = []
        for l,matrix in zip(lst, matrices):
                classDef2 = l.ClassDef2.classDefs
```

**Comment by anthrotype** [comment]
Miguel, I think we should create a branch here on the upstream repo that only contains the failing tests and the correct expected test data. Then, when Behdad or someone else finds the time to look into this they can commit directly to that branch.
I'll do it later today.

**Comment by anthrotype** [comment]
I don't think we want to modify the expected results to match the current output simply to make the test "pass". Ideally we would construct the expected TTX manually, then assert that the output matches these expectations, else fix the code to match that.

@miguelsousa Can you please close this PR and re-open it from a new branch here on upstream, instead of from your fork? It should only contain only the (failing) tests and the correct expected results. Then we could work together towards fixing the issue.

**Comment by miguelsousa** [comment]
The results are correct and were achieved by using `feaLib.builder.addOpenTypeFeaturesFromString` on a non-variable font, saving it, and then dumping the **GPOS** feature. This approach works because the output of `varLib.interpolate_layout` is an instance rather than a variable font.

@anthrotype yes I'll create the branch.

**Comment by miguelsousa** [comment]
Development moved to branch `class-kern-merge`.

**Comment by anthrotype** [comment]
Good! Also thanks for working on the CFF2CharStringPen 👍

**Comment by miguelsousa** [comment]
I'm taking a stab at it, but it's still too early to tell if I'll succeed.

**Pull request closed without merging**
