### PR TITLE
Compile a couple of modules with Cython when available

### PR DESCRIPTION
**Pull request by behdad**
Even with no annotations, makes varLib.iup ~35% faster, and varLib.interpolatable 3x faster (by way of pens.momentsPen).

### CODE REVIEW

**Comment by behdad** [comment]
I've pushed a couple small other commits here as well. Let me know if you prefer them as separate PRs.

**Comment by anthrotype** [comment]
Thanks! I think the last two commits (where you add support for reading .designspace and .glyphs files in varLib.interpolatable tool) could be split to a separate PR ideally

**Review by anthrotype — APPROVED** [review]
LGTM, except the last two commits that could be split to a spearate PR (for visibility mostly)

**Comment by behdad** [comment]
> Thanks! I think the last two commits (where you add support for reading .designspace and .glyphs files in varLib.interpolatable tool) could be split to a separate PR ideally

https://github.com/fonttools/fonttools/pull/2716

**Pull request merged**
