### PR TITLE
Fix bug in subsetting T2 CharStrings from CFF font, issue 1590

### PR DESCRIPTION
**Pull request by readroberts**
Fixes issue '[subset] AssertionError when using --desubroutinize #1590'

### CODE REVIEW

**Comment by anthrotype** [comment]
Thanks. Would be great if you could also add a test, maybe using the font that @khaledhosny uploaded to reproduce the issue in https://github.com/fonttools/fonttools/issues/1590

**Comment by anthrotype** [comment]
Thanks

**Comment by readroberts** [comment]
I'll add a test when I am back work on Tues.

**Comment by anthrotype** [comment]
Khaled already added one https://github.com/fonttools/fonttools/pull/1594/commits/b1999a1a0e7d7fb232e496eff5c6215d8b6aaebd

**Pull request merged**
