### PR TITLE
[varLib] Initialize the avar segment map with required default entries

### PR DESCRIPTION
**Pull request by jenskutilek**
All that remains of PR #1012

### CODE REVIEW

**Comment by anthrotype** [comment]
mind also adding a test?

**Comment by anthrotype** [comment]
In `Tests/varLib/varLib_test.py` we don't have a test with a designspace containing axis map elements, so that branch is not covered.
https://codecov.io/gh/fonttools/fonttools/src/2a67bddaeb59cab6d0ca48c88030a84759b2fdcc/Lib/fontTools/varLib/__init__.py#L94...120

**Comment by jenskutilek** [comment]
Would it be preferable to add completely new test data for this, or to integrate into one of the existing data files?

**Comment by anthrotype** [comment]
New specific data would be preferable

**Comment by anthrotype** [comment]
I mean, you can reuse the test master fonts, but a new designspace with axes map elements would be nic.

**Pull request merged**
