### PR TITLE
fix AttributeError while generating aalt feature with empty lookup

### PR DESCRIPTION
**Pull request by anthrotype**
mean to fix https://github.com/fonttools/fonttools/issues/2276

still trying to reproduce

### CODE REVIEW

**Comment by anthrotype** [comment]
the CI failure reproduces the `AttributeError: 'NoneType' object has no attribute 'getAlternateGlyphs'` error from #2276 
https://github.com/fonttools/fonttools/pull/2277/checks?check_run_id=2409640286#step:5:388

@kontur does the FEA code I used resemble what you're trying to do? namely this:

```
lookup EMPTY {
    # pass
} EMPTY;
feature ss01 {
    sub a by a.alt1;
    lookup EMPTY;
} ss01;
feature aalt {
    feature ss01;
} aalt;
```

**Comment by kontur** [comment]
@anthrotype yep, that's it. not sure how the aalt plays into it but the EMPTY and ss01 (scmp in my case) looks like what I encountered the problem with. Particularly if you replace "#pass" with something like "sub a by a;" and it does not throw the error then that seems to further confirm it.

**Comment by anthrotype** [comment]
what do you expect a FEA compiler to do with such an empty lookup? Ignore it altogether as if it was not there? Or still add an entry in the LookupList with a NULL offset that points to nothing?

the spec is silent about these
http://adobe-type-tools.github.io/afdko/OpenTypeFeatureFileSpecification.html#4e-lookup

**Comment by kontur** [comment]
I'd probably expect to drop it, but would there be sense in having in there for some merging of fonts? Not sure. 
Anyway, for me the empty lookup is just a "workflow" way of composing different features for slightly different fonts. For the most part that is better done with `include`s for shared parts or different class definitions, but in this case it seemed more convenient via the lookup.

**Comment by khaledhosny** [comment]
If makeotf accepts this, then we should do what it does (skip, add empty lookup, whatever), if it does not then I think erroring would be the safest action, otherwise adding an empty lookup. Silently ignoring the lookup would not be a good idea IMO.

**Comment by khaledhosny** [comment]
makeotf errors with the feature code above:
```
syntax error at "}" missing { feature script language subtable lookupflag enumerate except ignore substitute reverse position parameters feat_names sizemenuname markClass GCLASS ";" } [test.fea 3]
makeotfexe [FATAL] <Test-Regular> aborting because of errors
```

**Comment by simoncozens** [comment]
makeotf does, however, work with:

```
lookup EMPTY {
   ;
} EMPTY;
```

**Comment by khaledhosny** [comment]
Yes. It will ignore the lookup and the features that reference only it, so:
```fea
lookup EMPTY {
    ;
} EMPTY;
feature ss01 {
    lookup EMPTY;
} ss01;
feature aalt {
    feature ss01;
} aalt;
```

will not build any layout tables.

**Comment by anthrotype** [comment]
thanks for checking. So basically with this PR we're doing the same as makeotf, if I'm not mistaken.

If I change test fea file to add that empty semicolon statement:

```diff
lookup EMPTY {
-    # pass
+    ;
} EMPTY;
```

... the built output doesn't change, but the fea2fea tests fail because the duplicate semicolon is stripped by our parser.

Anyway, I think the current patch is correct, if the expectation is that references to empty named lookups should be ignored.

**Comment by anthrotype** [comment]
> would there be sense in having in there for some merging of fonts?

good question. /cc @behdad

**Comment by behdad** [comment]
> > would there be sense in having in there for some merging of fonts?
> 
> good question. /cc @behdad

My position is that we should always remove empty lookups. Lookup presence has no semantic value. Features do however sometimes. The case I know of currently is that HarfBuzz picks shaper for Khmer based on whether a `pref` feature is present. So in the subsetter, we keep the empty `pref` feature even if it has no lookups.

Merging shouldn't  be a problem.

**Comment by behdad** [comment]
Also I don't think we should do whatever AFDKO does. We should produce the output that makes most sense and is most compact.

**Comment by anthrotype** [comment]
> Merging shouldn't be a problem.

I believe he meant "merging" as in the `varLib.merger` module for making VFs, not just the`fonttools merge` script for static fonts. We currently require that the GPOS tables of each master are aligned such that they all have the same number and type of lookups (or no table at all, for "sparse" masters). But in the case of a truly empty lookup in feature file code (e.g. `lookup EMPTY { ; } EMPTY;`) the latter doesn't contain any pos/sub rules that would assign it a _type_, so it's really undefined. In this case it's safe to presume that such a no-op lookup is not present at all.
Whereas, a lookup that contains only zero values (https://github.com/fonttools/fonttools/pull/2275#issuecomment-824723754) does have a type and could, potentially, be used to make the GPOS masters align with one another to allow merging into a VF. Hm maybe just we need to think of a more granular way to specify "sparseness" for varLib.merger than "no table, or fully aligned table".

**Comment by behdad** [comment]
Right...

At some point we might implement better merging such that only features need to match, not lookups. Note that we already do more analysis within SinglePos and PairPos lookup types, aligning subtables. In theory we can do more.

**Comment by twardoch** [comment]
Yes, better v-merging of GPOS with sparse masters would be wonderful. It's quite a common source of problems.

**Pull request merged**
