### PR TITLE
[feaLib] fixed two instances of 'DeprecationWarning: invalid escape sequence'

### PR DESCRIPTION
**Pull request by justvanrossum**
...although I'm not sure what this backslash-space sequence is supposed to do.

### CODE REVIEW

**Comment by dscorbett** [comment]
The backslash suppresses the space between the code span and the ⟨s⟩. ``:class:`LookupBlock`\ s`` is rendered ⟨`LookupBlock`s⟩ whereas ``:class:`LookupBlock` s`` is rendered ⟨`LookupBlock` s⟩. The space is necessary because ``:class:`LookupBlock`s`` is rendered literally ⟨:class:\`LookupBlock\`s⟩ plus a warning message.

**Comment by justvanrossum** [comment]
> The backslash suppresses the space between the code span [ ... ]

Thanks.

The alternative fix for the warning is to make these doc strings "raw" strings: `r"Abc \ def"`. Any preference?

**Comment by dscorbett** [comment]
As long as the output documentation looks the same, I have no preference for the type of docstring.

**Comment by anthrotype** [comment]
+1 for ``r""":class:`LookupBlock`\ s"""``

**Pull request merged**
