### PR TITLE
Revert "[varLib.models] Generate narrower tents"

### PR DESCRIPTION
**Pull request by anthrotype**
This reverts commit 688939394b8cae3b2a0d5747e435cbd828a14531.

### CODE REVIEW

**Comment by anthrotype** [comment]
temporarily works around https://github.com/fonttools/fonttools/issues/2764

**Comment by behdad** [comment]
Ah, thanks. I was on it. :)

**Comment by anthrotype** [comment]
oh, ok ! it broke a couple tests, had to fix manually, let me know if they still make sense

**Review by behdad — APPROVED** [review]

**Comment by behdad** [comment]
> oh, ok ! it broke a couple tests, had to fix manually, let me know if they still make sense

Yes. I was doing the same.

**Comment by anthrotype** [comment]
i'll merge once CI passes and then cut bugfix release

**Comment by behdad** [comment]
Now we should add test case from Just's bug report. I'll see if I can add that now.

**Comment by behdad** [comment]
> Now we should add test case from Just's bug report. I'll see if I can add that now.

Don't wait for that though, obviously.

**Comment by anthrotype** [comment]
i also need to fix the doctests..

**Comment by behdad** [comment]
Test addded.

**Pull request merged**
