### PR TITLE
Minor fixes to documentation for merge

### PR DESCRIPTION
**Pull request by drj11**
Mostly fixing the explanation of how glyphs get renamed (they get `.n` added, not `#n`), but couldn't resist a couple of other minor fixups too.

### CODE REVIEW

**Comment by behdad** [comment]
> By the way, i'm not sure that the sentence "If duplicate glyph disambiguation takes place as described above then the fonts must have a GSUB table." is true (any more?). For example the following works and the fontfile does not have a GSUB table.

We do the disambiguation only if the two glyphs have different shapes. I'll try to update the documentation.

**Comment by behdad** [comment]
> > By the way, i'm not sure that the sentence "If duplicate glyph disambiguation takes place as described above then the fonts must have a GSUB table." is true (any more?). For example the following works and the fontfile does not have a GSUB table.
> 
> We do the disambiguation only if the two glyphs have different shapes. I'll try to update the documentation.

Looks like the docu already mentions that.

**Comment by drj11** [comment]
Oh yes, i did actually read that. It doesn't work, or there is something more subtle going on.

The merged TTF has double the number of glyphs (TTF is from https://github.com/google/fonts/tree/main/apache/craftygirls by the way)

```
; otfinfo --glyphs CraftyGirls-Regular.ttf | wc
     230     230    1604
; otfinfo --glyphs merged.ttf | wc
     460     460    3668
```

**Comment by behdad** [comment]
The merge tool is very incomplete and unmaintained unfortunately...

I suspect we add the duplicate glyph, just never use it...

**Comment by drj11** [comment]
Fair enough. i was poking around because i was thinking of writing a merging tool. :)

**Comment by behdad** [comment]
All yours to take. As we say: "you touch it you own it". :D

**Pull request merged**
