### PR TITLE
Add Snippets/post-format.py

### PR DESCRIPTION
**Pull request by davelab6**
I wrote this for myself just now, figured it would best live here :)

### CODE REVIEW

**Comment by behdad** [comment]
I'm more and more being convinced that I need to work out pyftshell or something.  Then you can do things like:
```
  pyftshell -e 'print(fontfile, font["post"].format)' *.ttf
```
adding scripts like this is really a futile exercise.

**Comment by twardoch** [comment]
That'd be cool. It sounds a bit like 
https://amoffat.github.io/sh/
which I may start using instead of the subprocess crap in my tools.

**Comment by davelab6** [comment]
That would rock! That would make it much easier to develop nototools/fontbakery/etc :)

**Comment by davelab6** [comment]
I played around with trying this as a python 1-liner and had no luck, so yes, a `pyftshell` that took care of common sharp edges for that kind of thing would be really great :)

    for font in `find . -name \*.\*tf -print`; do \
      python -c "from fontTools.ttLib import TTFont; print(str(TTFont('"$font"')['post'].formatType))" | sort | cut -d\  -f1 | uniq -c ; \
	done;

I simplified the script; if you want to reject it, no problem, I'll put it elsewhere

**Pull request closed without merging**
